import { adminDb } from './firebaseAdmin';
import {
  User,
  ProcessItem,
  MatrizAlcada,
  RegraAlcada,
  Solicitacao,
  AuditLog,
  SystemNotification,
  SystemConfig,
} from '../types';

// In-memory data store with transactional methods and seed data
class Database {
  users: User[] = [];
  processes: ProcessItem[] = [];
  matrices: MatrizAlcada[] = [];
  requests: Solicitacao[] = [];
  auditLogs: AuditLog[] = [];
  notifications: SystemNotification[] = [];
  config: SystemConfig = {
    id: 'cfg-default',
    diasUteisAlertaVencimento: 5,
    janelaDiasDeteccaoFracionamento: 30,
    bloquearEstouroTetoMensal: false,
    exigirOtpLogin: false,
    restringirDominioGoogleOAuth: false,
    dominioPermitido: '@sbsaude.com.br',
    slaAprovacaoHoras: 48,
    sgqRepositorioCodigo: 'POL-DIR-01 / FOR-FIN-01 (ISO 9001:2015 7.5)',
    tempoRetencaoAnos: 2,
  };
  otpCodes: Map<string, { code: string; expiresAt: number }> = new Map();

  
  public async loadFromFirestore() {
    try {
      const usersSnap = await adminDb.collection('users').get();
      if (!usersSnap.empty) {
        this.users = usersSnap.docs.map(d => d.data() as User);
      }
      const processSnap = await adminDb.collection('processes').get();
      if (!processSnap.empty) {
        this.processes = processSnap.docs.map(d => d.data() as ProcessItem);
      }
      const matricesSnap = await adminDb.collection('matrices').get();
      if (!matricesSnap.empty) {
        this.matrices = matricesSnap.docs.map(d => d.data() as MatrizAlcada);
      }
      const requestsSnap = await adminDb.collection('requests').get();
      if (!requestsSnap.empty) {
        this.requests = requestsSnap.docs.map(d => d.data() as Solicitacao);
      }
      const logsSnap = await adminDb.collection('auditLogs').get();
      if (!logsSnap.empty) {
        this.auditLogs = logsSnap.docs.map(d => d.data() as AuditLog);
      }
      const notifsSnap = await adminDb.collection('notifications').get();
      if (!notifsSnap.empty) {
        this.notifications = notifsSnap.docs.map(d => d.data() as SystemNotification);
      }
      const configSnap = await adminDb.collection('config').doc('cfg-default').get();
      if (configSnap.exists) {
        this.config = configSnap.data() as SystemConfig;
      } else {
        // save default
        await this.syncToFirestore('config', 'cfg-default', this.config);
      }
      
      // If users empty, run seed and save to Firestore
      if (this.users.length === 0) {
        // this.seed(); defer to loadFromFirestore
        for (const u of this.users) await this.syncToFirestore('users', u.id, u);
        for (const p of this.processes) await this.syncToFirestore('processes', p.id, p);
        for (const m of this.matrices) await this.syncToFirestore('matrices', m.id, m);
      }
    } catch(e) {
      console.error('Failed to load from Firestore', e);
    }
  }

  public async syncToFirestore(collection: string, docId: string, data: any) {
    try {
      await adminDb.collection(collection).doc(docId).set(data, { merge: true });
    } catch (e) {
      console.error('Firestore sync error:', e);
    }
  }

  public async deleteFromFirestore(collection: string, docId: string) {
    try {
      await adminDb.collection(collection).doc(docId).delete();
    } catch (e) {
      console.error('Firestore delete error:', e);
    }
  }

  constructor() {
    this.seed();
  }

  private seed() {
    // 1. Seed Users (SB Saúde structure)
    this.users = [
      {
        id: 'usr-1',
        name: 'Raquel Marimon',
        email: 'raquel.marimon@sbsaude.com.br',
        cargo: 'Analista de Gente e Gestão',
        area: 'Gente e Gestão',
        centroCusto: 'CC-1010 - Recursos Humanos',
        phone: '(11) 98765-4321',
        roles: ['SOLICITANTE'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-2',
        name: 'Haroldo Peon',
        email: 'haroldo.peon@sbsaude.com.br',
        cargo: 'Supervisor de Credenciamento',
        area: 'Credenciamento',
        centroCusto: 'CC-2020 - Rede Credenciada',
        phone: '(11) 98765-1111',
        roles: ['APROVADOR_1'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-3',
        name: 'Janine Sena',
        email: 'janine.sena@sbsaude.com.br',
        cargo: 'Coordenadora de Finanças',
        area: 'Finanças e Controladoria',
        centroCusto: 'CC-3030 - Finanças',
        phone: '(11) 98765-2222',
        roles: ['APROVADOR_1'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-4',
        name: 'Christiane Macedo',
        email: 'christiane.macedo@sbsaude.com.br',
        cargo: 'Gerente de Credenciamento e Núcleo Assistencial',
        area: 'Núcleo Assistencial',
        centroCusto: 'CC-2020 - Rede Credenciada',
        phone: '(11) 98765-3333',
        roles: ['APROVADOR_2'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-5',
        name: 'Dr. Carlos Eduardo',
        email: 'carlos.eduardo@sbsaude.com.br',
        cargo: 'Gerente de COM & MKT',
        area: 'Comunicação e Marketing',
        centroCusto: 'CC-4040 - Marketing',
        phone: '(11) 98765-4444',
        roles: ['APROVADOR_2'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-6',
        name: 'Dra. Mariana Silva',
        email: 'mariana.silva@sbsaude.com.br',
        cargo: 'Diretora de Operações',
        area: 'Diretoria de Operações',
        centroCusto: 'CC-5050 - Operações',
        phone: '(11) 98765-5555',
        roles: ['APROVADOR_3'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-7',
        name: 'Roberto Guimarães',
        email: 'roberto.guimaraes@sbsaude.com.br',
        cargo: 'Diretor Financeiro',
        area: 'Diretoria Financeira',
        centroCusto: 'CC-3030 - Finanças',
        phone: '(11) 98765-6666',
        roles: ['APROVADOR_3'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-8',
        name: 'Janaína Mascarenhas',
        email: 'janaina.mascarenhas@sbsaude.com.br',
        cargo: 'Diretoria Executiva / Conselho',
        area: 'Presidência Executiva',
        centroCusto: 'CC-9090 - Conselho Executivo',
        phone: '(11) 98765-7777',
        roles: ['APROVADOR_4'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-9',
        name: 'Patrícia Mendes',
        email: 'patricia.mendes@sbsaude.com.br',
        cargo: 'Analista de Contas a Pagar / Financeiro',
        area: 'Contas a Pagar',
        centroCusto: 'CC-3030 - Finanças',
        phone: '(11) 98765-8888',
        roles: ['FINANCEIRO'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-10',
        name: 'Fernando Rocha',
        email: 'fernando.rocha@sbsaude.com.br',
        cargo: 'Coordenador de Tesouraria',
        area: 'Tesouraria',
        centroCusto: 'CC-3030 - Finanças',
        phone: '(11) 98765-9999',
        roles: ['TESOURARIA'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-11',
        name: 'Vanessa Duarte',
        email: 'vanessa.duarte@sbsaude.com.br',
        cargo: 'Gerente de Governança e SGQ / Admin',
        area: 'Governança e Qualidade',
        centroCusto: 'CC-8080 - Governança SGQ',
        phone: '(11) 98765-0000',
        roles: ['ADMINISTRADOR'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
    ];

    // 2. Seed All Processes from POL-DIR-01
    const rawProcesses: Array<Omit<ProcessItem, 'createdAt' | 'updatedAt'>> = [
      {
        id: 'proc-01',
        code: 'PRC-DEMISSOES-ALTO-RISCO',
        name: 'Demissões de alto risco jurídico ou envolvendo cargos estratégicos',
        description: 'Desligamentos estratégicos ou com potencial de litígio trabalhista relevante',
        natureza: 'RH',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-02',
        code: 'PRC-COMPRAS-TI',
        name: 'Compras de equipamento e outras demandas de tecnologia da informação (TI)',
        description: 'Aquisição de hardware, infraestrutura de servidores e licenças de software corporativo',
        natureza: 'TI',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-03',
        code: 'PRC-PRESTADORES-REDE',
        name: 'Pagamento de prestadores (Rede)',
        description: 'Honorários médicos, clínicas, laboratórios e rede hospitalar credenciada',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-04',
        code: 'PRC-PARTOS-EMERGENCIAIS',
        name: 'Autorização de partos Emergenciais / Eletivos',
        description: 'Procedimentos obstétricos e partos em maternidades parceiras',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-05',
        code: 'PRC-PAGAMENTOS-DIVERSOS-DIR',
        name: 'Autorização de pagamentos diversos (Diretoria)',
        description: 'Despesas extraordinárias e demandas estratégicas corporativas',
        natureza: 'FINANCEIRO',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-06',
        code: 'PRC-CIRURGIA-EMERGENCIAL',
        name: 'Autorização de cirurgia emergencial',
        description: 'Cirurgias urgentes e intervenções hospitalares imediatas',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-07',
        code: 'PRC-ONCO-CRONICOS-ALTA',
        name: 'Procedimentos oncológicos/Crônicos de maior complexidade (acima R$ 2.001,00)',
        description: 'Tratamentos oncológicos contínuos, quimioterapia, imunoterapia e terapias de alto custo',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-08',
        code: 'PRC-CIRURGIAS-JUDICIAIS',
        name: 'Autorização de Cirurgias provenientes de processos judiciais',
        description: 'Cumprimento de liminares e determinações judiciais para cirurgias',
        natureza: 'JURIDICO',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-09',
        code: 'PRC-NIPS-ELETIVAS',
        name: 'Autorização de NIPs eletivas',
        description: 'Demandas da Notificação de Intermediação Preliminar da ANS em caráter eletivo',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-10',
        code: 'PRC-PREPAG-CONSULTAS-EXAMES',
        name: 'Pré pagamentos de consultas e exames eletivo',
        description: 'Adiantamento e pré-pagamento para clínicas e laboratórios de rotina',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-11',
        code: 'PRC-NIP-URGENCIA',
        name: 'Autorização de NIP de urgência',
        description: 'Notificação de Intermediação Preliminar ANS com prazo urgente/crítico',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-12',
        code: 'PRC-PREPAG-NIPEIROS',
        name: 'Pré pagamentos de beneficiários com reclamações reincidentes (Nipeiros)',
        description: 'Liberação assistencial para mitigação de riscos de reincidência perante a ANS',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-13',
        code: 'PRC-REEMBOLSO',
        name: 'Reembolso',
        description: 'Reembolso de despesas médico-hospitalares conforme contrato do plano',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-14',
        code: 'PRC-ACORDOS-JUDICIAIS',
        name: 'Autorização de Acordos Judiciais',
        description: 'Homologação e pagamentos de acordos e conciliações cíveis e assistenciais',
        natureza: 'JURIDICO',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-15',
        code: 'PRC-ANESTESIAS',
        name: 'Autorização de Anestesias',
        description: 'Honorários de equipes anestésicas e cooperativas anestesiológicas',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-16',
        code: 'PRC-ACOES-EXTERNAS-MKT',
        name: 'Ações Externas (Parceiros / Corretores / Beneficiários)',
        description: 'Eventos institucionais externos, stands, relacionamento e premiações',
        natureza: 'MARKETING',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-17',
        code: 'PRC-POS-VENDA',
        name: 'Pagamentos de demandas do Pós Venda',
        description: 'Ressarcimentos e adequações contratuais pós-adesão',
        natureza: 'OPERACIONAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-18',
        code: 'PRC-INFLUENCER-MIDIA',
        name: 'Influencer Mídia',
        description: 'Contratação de influenciadores e campanhas de alcance em mídias sociais',
        natureza: 'MARKETING',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-19',
        code: 'PRC-PROC-AMB-ACIMA-2K',
        name: 'Procedimentos ambulatoriais eletivos (acima de R$ 2.001,00)',
        description: 'Consultas especializadas e procedimentos ambulatoriais de maior custo',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-20',
        code: 'PRC-CIRURGIAS-MAIOR-COMPLEX',
        name: 'Cirurgias de maior complexidade (acima R$ 2.001,00)',
        description: 'Intervenções cirúrgicas de médio e grande porte',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-21',
        code: 'PRC-PROC-AMB-ATE-2K',
        name: 'Procedimentos ambulatoriais eletivos (até R$ 2.000,00)',
        description: 'Exames e consultas de rotina em clínicas credenciadas',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-22',
        code: 'PRC-CIRURGIAS-MENOR-COMPLEX',
        name: 'Cirurgias de menor complexidade (até R$ 2.000,00)',
        description: 'Pequenas cirurgias e procedimentos de curta permanência',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-23',
        code: 'PRC-ONCO-CRONICOS-ATE-2K',
        name: 'Procedimentos oncológicos / Crônicos de menor complexidade (até R$ 2.000,00)',
        description: 'Medicamentos orais e aplicações de suporte ambulatorial oncológico',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-24',
        code: 'PRC-CAMPANHAS-INTERNAS',
        name: 'Campanhas Internas',
        description: 'Comunicação interna, endomarketing e eventos com colaboradores',
        natureza: 'MARKETING',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-25',
        code: 'PRC-PROJETO-SOCIAL',
        name: 'Projeto Social "Alguém Que Se Importa"',
        description: 'Iniciativas sociais e ações humanitárias institucionais SB Saúde',
        natureza: 'MARKETING',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-26',
        code: 'PRC-PAGAMENTOS-DIVERSOS-FIN',
        name: 'Autorização de pagamentos diversos (Finanças)',
        description: 'Taxas, emolumentos, serviços cartorários e despesas operacionais rotineiras',
        natureza: 'FINANCEIRO',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-27',
        code: 'PRC-DEMISSOES-BAIXO-RISCO',
        name: 'Demissões sem justa causa de baixo risco jurídico',
        description: 'Rescisões contratuais padrão de colaboradores operacionais',
        natureza: 'RH',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: false,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-28',
        code: 'PRC-ACORDOS-TRABALHISTAS',
        name: 'Acordos trabalhistas até um valor pré-definido',
        description: 'Transações e acordos em câmaras de conciliação trabalhista',
        natureza: 'JURIDICO',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-29',
        code: 'PRC-ACOES-INTERNAS-EVENTUAIS',
        name: 'Ações Internas Eventuais',
        description: 'Comemorações, premiações de equipes e ações de engajamento',
        natureza: 'MARKETING',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-30',
        code: 'PRC-FORNECEDORES-ADM-RH',
        name: 'Contratação de fornecedores para atender as demandas administrativas e recursos humanos',
        description: 'Serviços de limpeza, manutenção predial, suprimentos e apoio operacional',
        natureza: 'ADMINISTRATIVO',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-31',
        code: 'PRC-TREINAMENTOS-RH',
        name: 'Contratação de treinamentos e consultorias de RH dentro do orçamento',
        description: 'Capacitações técnicas, cursos e consultorias especializadas',
        natureza: 'RH',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-32',
        code: 'PRC-PROMOCOES-SALARIAIS',
        name: 'Promoções e movimentações internas com impacto salarial até determinado limite (ex.: até 10% de aumento)',
        description: 'Ajustes no plano de cargos e salários e promoções de mérito',
        natureza: 'RH',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-33',
        code: 'PRC-TRAFEGO-PAGO',
        name: 'Tráfego Pago (Instagram)',
        description: 'Investimento em anúncios digitais, meta ads e campanhas de captação',
        natureza: 'MARKETING',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-34',
        code: 'PRC-BENEFICIOS-NAO-OBRIGATORIOS',
        name: 'Benefícios não obrigatórios dentro de orçamento aprovado',
        description: 'Subsídios, convênios e benefícios opcionais para o quadro funcional',
        natureza: 'RH',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
    ];

    this.processes = rawProcesses.map((p) => ({
      ...p,
      createdAt: '2026-07-07T09:00:00Z',
      updatedAt: '2026-07-07T09:00:00Z',
    }));

    // 3. Seed Matrix POL-DIR-01 Rev. 00
    const rules: RegraAlcada[] = [
      {
        id: 'rule-01',
        matrizId: 'mtz-00',
        processoId: 'proc-01',
        processoNome: 'Demissões de alto risco jurídico ou envolvendo cargos estratégicos',
        risco: 'ALTO',
        alçadaPorEvento: 0,
        tetoMensal: 0,
        cargosHabilitados1: ['Diretoria de Operações'],
        cargosHabilitados2: ['Diretoria Financeira'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-02',
        matrizId: 'mtz-00',
        processoId: 'proc-02',
        processoNome: 'Compras de equipamento e outras demandas de tecnologia da informação (TI)',
        risco: 'BAIXO',
        alçadaPorEvento: 0,
        tetoMensal: 0,
        cargosHabilitados1: ['DIRETORIA FINANCEIRA', 'Diretor Financeiro'],
        nivelMaximoRequerido: 1,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-03',
        matrizId: 'mtz-00',
        processoId: 'proc-03',
        processoNome: 'Pagamento de prestadores (Rede)',
        risco: 'ALTO',
        alçadaPorEvento: 150000,
        tetoMensal: 500000,
        cargosHabilitados1: ['Gerente Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-04',
        matrizId: 'mtz-00',
        processoId: 'proc-04',
        processoNome: 'Autorização de partos Emergenciais / Eletivos',
        risco: 'ALTO',
        alçadaPorEvento: 25000,
        tetoMensal: 70000,
        cargosHabilitados1: ['Acolhimento a Gestantes', 'Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Núcleo Assistencial', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados4: ['Diretoria Financeira', 'Diretoria Executiva / Conselho'],
        nivelMaximoRequerido: 4,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-05',
        matrizId: 'mtz-00',
        processoId: 'proc-05',
        processoNome: 'Autorização de pagamentos diversos (Diretoria)',
        risco: 'ALTO',
        alçadaPorEvento: 25000,
        tetoMensal: 100000,
        cargosHabilitados1: ['Diretora de Operações', 'Diretoria de Operações'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-06',
        matrizId: 'mtz-00',
        processoId: 'proc-06',
        processoNome: 'Autorização de cirurgia emergencial',
        risco: 'ALTO',
        alçadaPorEvento: 20000,
        tetoMensal: 80000,
        cargosHabilitados1: ['Gerente Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-07',
        matrizId: 'mtz-00',
        processoId: 'proc-07',
        processoNome: 'Procedimentos oncológicos/Crônicos de maior complexidade (acima R$ 2.001,00)',
        risco: 'ALTO',
        alçadaPorEvento: 20000,
        tetoMensal: 80000,
        cargosHabilitados1: ['Gerência de Núcleo Assistencial', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-08',
        matrizId: 'mtz-00',
        processoId: 'proc-08',
        processoNome: 'Autorização de Cirurgias provenientes de processos judiciais',
        risco: 'ALTO',
        alçadaPorEvento: 20000,
        tetoMensal: 40000,
        cargosHabilitados1: ['Coordenador de Núcleo Regulatório', 'Supervisor de Credenciamento'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-09',
        matrizId: 'mtz-00',
        processoId: 'proc-09',
        processoNome: 'Autorização de NIPs eletivas',
        risco: 'ALTO',
        alçadaPorEvento: 12500,
        tetoMensal: 50000,
        cargosHabilitados1: ['Coordenador Núcleo de Experiência do Beneficiário', 'Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-10',
        matrizId: 'mtz-00',
        processoId: 'proc-10',
        processoNome: 'Pré pagamentos de consultas e exames eletivo',
        risco: 'MEDIO',
        alçadaPorEvento: 13000,
        tetoMensal: 52000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-11',
        matrizId: 'mtz-00',
        processoId: 'proc-11',
        processoNome: 'Autorização de NIP de urgência',
        risco: 'ALTO',
        alçadaPorEvento: 10000,
        tetoMensal: 40000,
        cargosHabilitados1: ['Coordenador Núcleo de Experiência do Beneficiário', 'Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-12',
        matrizId: 'mtz-00',
        processoId: 'proc-12',
        processoNome: 'Pré pagamentos de beneficiários com reclamações reincidentes (Nipeiros)',
        risco: 'ALTO',
        alçadaPorEvento: 5000,
        tetoMensal: 20000,
        cargosHabilitados1: ['Gerente da Qualidade', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-13',
        matrizId: 'mtz-00',
        processoId: 'proc-13',
        processoNome: 'Reembolso',
        risco: 'MEDIO',
        alçadaPorEvento: 5000,
        tetoMensal: 20000,
        cargosHabilitados1: ['Gerência de Núcleo Assistencial', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-14',
        matrizId: 'mtz-00',
        processoId: 'proc-14',
        processoNome: 'Autorização de Acordos Judiciais',
        risco: 'ALTO',
        alçadaPorEvento: 5000,
        tetoMensal: 20000,
        cargosHabilitados1: ['Coordenador de Núcleo Regulatório', 'Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-15',
        matrizId: 'mtz-00',
        processoId: 'proc-15',
        processoNome: 'Autorização de Anestesias',
        risco: 'MEDIO',
        alçadaPorEvento: 3000,
        tetoMensal: 12000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-16',
        matrizId: 'mtz-00',
        processoId: 'proc-16',
        processoNome: 'Ações Externas (Parceiros / Corretores / Beneficiários)',
        risco: 'ALTO',
        alçadaPorEvento: 3000,
        tetoMensal: 3000,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-17',
        matrizId: 'mtz-00',
        processoId: 'proc-17',
        processoNome: 'Pagamentos de demandas do Pós Venda',
        risco: 'MEDIO',
        alçadaPorEvento: 2500,
        tetoMensal: 10000,
        cargosHabilitados1: ['Coordenadora Comercial', 'Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-18',
        matrizId: 'mtz-00',
        processoId: 'proc-18',
        processoNome: 'Influencer Mídia',
        risco: 'MEDIO',
        alçadaPorEvento: 2500,
        tetoMensal: 2500,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-19',
        matrizId: 'mtz-00',
        processoId: 'proc-19',
        processoNome: 'Procedimentos ambulatoriais eletivos (acima de R$ 2.001,00)',
        risco: 'BAIXO',
        alçadaPorEvento: 2001,
        tetoMensal: 60000,
        cargosHabilitados1: ['Gerência de Núcleo Assistencial', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-20',
        matrizId: 'mtz-00',
        processoId: 'proc-20',
        processoNome: 'Cirurgias de maior complexidade (acima R$ 2.001,00)',
        risco: 'ALTO',
        alçadaPorEvento: 2001,
        tetoMensal: 50000,
        cargosHabilitados1: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-21',
        matrizId: 'mtz-00',
        processoId: 'proc-21',
        processoNome: 'Procedimentos ambulatoriais eletivos (até R$ 2.000,00)',
        risco: 'BAIXO',
        alçadaPorEvento: 2000,
        tetoMensal: 8000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-22',
        matrizId: 'mtz-00',
        processoId: 'proc-22',
        processoNome: 'Cirurgias de menor complexidade (até R$ 2.000,00)',
        risco: 'MEDIO',
        alçadaPorEvento: 2000,
        tetoMensal: 8000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-23',
        matrizId: 'mtz-00',
        processoId: 'proc-23',
        processoNome: 'Procedimentos oncológicos / Crônicos de menor complexidade (até R$ 2.000,00)',
        risco: 'ALTO',
        alçadaPorEvento: 2000,
        tetoMensal: 8000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-24',
        matrizId: 'mtz-00',
        processoId: 'proc-24',
        processoNome: 'Campanhas Internas',
        risco: 'BAIXO',
        alçadaPorEvento: 2000,
        tetoMensal: 2000,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-25',
        matrizId: 'mtz-00',
        processoId: 'proc-25',
        processoNome: 'Projeto Social "Alguém Que Se Importa"',
        risco: 'BAIXO',
        alçadaPorEvento: 2000,
        tetoMensal: 2000,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-26',
        matrizId: 'mtz-00',
        processoId: 'proc-26',
        processoNome: 'Autorização de pagamentos diversos (Finanças)',
        risco: 'MEDIO',
        alçadaPorEvento: 2000,
        tetoMensal: 10000,
        cargosHabilitados1: ['Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-27',
        matrizId: 'mtz-00',
        processoId: 'proc-27',
        processoNome: 'Demissões sem justa causa de baixo risco jurídico',
        risco: 'ALTO',
        alçadaPorEvento: 1500,
        tetoMensal: 6000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-28',
        matrizId: 'mtz-00',
        processoId: 'proc-28',
        processoNome: 'Acordos trabalhistas até um valor pré-definido',
        risco: 'MEDIO',
        alçadaPorEvento: 1500,
        tetoMensal: 6000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-29',
        matrizId: 'mtz-00',
        processoId: 'proc-29',
        processoNome: 'Ações Internas Eventuais',
        risco: 'ALTO',
        alçadaPorEvento: 1000,
        tetoMensal: 1000,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-30',
        matrizId: 'mtz-00',
        processoId: 'proc-30',
        processoNome: 'Contratação de fornecedores para atender as demandas administrativas e recursos humanos',
        risco: 'MEDIO',
        alçadaPorEvento: 750,
        tetoMensal: 3000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-31',
        matrizId: 'mtz-00',
        processoId: 'proc-31',
        processoNome: 'Contratação de treinamentos e consultorias de RH dentro do orçamento',
        risco: 'BAIXO',
        alçadaPorEvento: 600,
        tetoMensal: 2400,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-32',
        matrizId: 'mtz-00',
        processoId: 'proc-32',
        processoNome: 'Promoções e movimentações internas com impacto salarial até determinado limite (ex.: até 10% de aumento)',
        risco: 'BAIXO',
        alçadaPorEvento: 500,
        tetoMensal: 2000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-33',
        matrizId: 'mtz-00',
        processoId: 'proc-33',
        processoNome: 'Tráfego Pago (Instagram)',
        risco: 'ALTO',
        alçadaPorEvento: 500,
        tetoMensal: 500,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-34',
        matrizId: 'mtz-00',
        processoId: 'proc-34',
        processoNome: 'Benefícios não obrigatórios dentro de orçamento aprovado',
        risco: 'BAIXO',
        alçadaPorEvento: 250,
        tetoMensal: 1000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria De Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
    ];

    this.matrices = [
      {
        id: 'mtz-00',
        codigo: 'POL-DIR-01',
        versao: 'Rev. 00',
        titulo: 'Política de Alçada e Delegação de Autoridade (Vigência 2026-2028)',
        status: 'VIGENTE',
        vigenciaInicio: '2026-07-07',
        vigenciaFim: '2028-07-07',
        elaboracao: 'Raquel Marimon / Janine Sena',
        revisao: 'Christiane Macedo / Haroldo Peon',
        aprovacao: 'Janaína Mascarenhas',
        publicadoPor: 'Vanessa Duarte (SGQ)',
        publicadoEm: '2026-07-07T10:00:00Z',
        historicoAlteracoes: 'Emissão Inicial aprovada pela Diretoria Executiva conforme RN ANS nº 518/2022 e ISO 9001:2015.',
        regras: rules,
        createdAt: '2026-07-07T08:00:00Z',
        updatedAt: '2026-07-07T10:00:00Z',
      },
    ];

    // 4. No transactional seed data — production starts with zero requests, audit logs and notifications
    this.requests = [];

    // 5. Seed Initial Audit Logs
    this.auditLogs = [];

    // 6. Seed Notifications
    this.notifications = [];
  }

  // --- Transactions & Helpers ---

  getNextRequestNumber(): { numero: string; sequencial: number; ano: number } {
    const currentYear = new Date().getFullYear();
    const requestsThisYear = this.requests.filter((r) => r.ano === currentYear);
    const maxSeq = requestsThisYear.reduce((max, r) => Math.max(max, r.sequencial), 0);
    const sequencial = maxSeq + 1;
    const padded = String(sequencial).padStart(4, '0');
    return {
      numero: `FIN-ALC-${padded}/${currentYear}`,
      sequencial,
      ano: currentYear,
    };
  }

  addAuditLog(log: Omit<AuditLog, 'id' | 'timestamp'>): AuditLog {
    const newLog: AuditLog = {
      id: `aud-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      ...log,
      timestamp: new Date().toISOString(),
    };
    // Logs are strictly immutable: append-only
    this.auditLogs.unshift(newLog);
    return newLog;
  }

  addNotification(notif: Omit<SystemNotification, 'id' | 'createdAt' | 'lida'>): SystemNotification {
    const newNotif: SystemNotification = {
      id: `notif-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      ...notif,
      lida: false,
      createdAt: new Date().toISOString(),
    };
    this.notifications.unshift(newNotif);
    return newNotif;
  }
}

export const db = new Database();
