import { adminDb } from './firebaseAdmin';
import {
  User,
  ProcessItem,
  MatrizAlcada,
  RegraAlcada,
  Solicitacao,
  AuditLog,
  SystemNotification,
  SystemConfig,
} from '../types';

// In-memory data store with transactional methods and seed data
class Database {
  users: User[] = [];
  processes: ProcessItem[] = [];
  matrices: MatrizAlcada[] = [];
  requests: Solicitacao[] = [];
  auditLogs: AuditLog[] = [];
  notifications: SystemNotification[] = [];
  config: SystemConfig = {
    id: 'cfg-default',
    diasUteisAlertaVencimento: 5,
    janelaDiasDeteccaoFracionamento: 30,
    bloquearEstouroTetoMensal: false,
    exigirOtpLogin: false,
    restringirDominioGoogleOAuth: false,
    dominioPermitido: '@sbsaude.com.br',
    slaAprovacaoHoras: 48,
    sgqRepositorioCodigo: 'POL-DIR-01 / FOR-FIN-01 (ISO 9001:2015 7.5)',
    tempoRetencaoAnos: 2,
  };
  otpCodes: Map<string, { code: string; expiresAt: number }> = new Map();

  
  public async loadFromFirestore() {
    try {
      console.log('[DB] Carregando dados do Firestore...');

      const usersSnap = await adminDb.collection('users').get();
      if (!usersSnap.empty) {
        this.users = usersSnap.docs.map(d => ({ id: d.id, ...d.data() } as User));
        console.log(`[DB] ${this.users.length} usuários carregados.`);
      }

      const processSnap = await adminDb.collection('processes').get();
      if (!processSnap.empty) {
        this.processes = processSnap.docs.map(d => ({ id: d.id, ...d.data() } as ProcessItem));
        console.log(`[DB] ${this.processes.length} processos carregados.`);
      }

      const matricesSnap = await adminDb.collection('matrices').get();
      if (!matricesSnap.empty) {
        const matrices: MatrizAlcada[] = [];
        for (const doc of matricesSnap.docs) {
          const matrixData = { id: doc.id, ...doc.data() } as MatrizAlcada;
          // Load subcollection rules
          const rulesSnap = await adminDb.collection('matrices').doc(doc.id).collection('rules').get();
          if (!rulesSnap.empty) {
            matrixData.regras = rulesSnap.docs.map(r => ({ id: r.id, ...r.data() } as RegraAlcada));
          } else if (!matrixData.regras) {
            matrixData.regras = [];
          }
          matrices.push(matrixData);
        }
        this.matrices = matrices;
        console.log(`[DB] ${this.matrices.length} matrizes carregadas.`);
      }

      const requestsSnap = await adminDb.collection('requests').get();
      if (!requestsSnap.empty) {
        this.requests = requestsSnap.docs.map(d => ({ id: d.id, ...d.data() } as Solicitacao));
        console.log(`[DB] ${this.requests.length} solicitações carregadas.`);
      }

      const logsSnap = await adminDb.collection('auditLogs').orderBy('timestamp', 'desc').limit(500).get();
      if (!logsSnap.empty) {
        this.auditLogs = logsSnap.docs.map(d => ({ id: d.id, ...d.data() } as AuditLog));
        console.log(`[DB] ${this.auditLogs.length} logs de auditoria carregados.`);
      }

      const notifsSnap = await adminDb.collection('notifications').orderBy('createdAt', 'desc').limit(200).get();
      if (!notifsSnap.empty) {
        this.notifications = notifsSnap.docs.map(d => ({ id: d.id, ...d.data() } as SystemNotification));
        console.log(`[DB] ${this.notifications.length} notificações carregadas.`);
      }

      const configSnap = await adminDb.collection('config').doc('cfg-default').get();
      if (configSnap.exists) {
        this.config = configSnap.data() as SystemConfig;
        console.log('[DB] Configurações do sistema carregadas.');
      } else {
        // Persist default config
        await this.syncToFirestore('config', 'cfg-default', this.config);
        console.log('[DB] Configurações padrão salvas no Firestore.');
      }

      // If no data found, seed and persist to Firestore
      if (this.users.length === 0) {
        console.log('[DB] Nenhum dado encontrado. Iniciando seed inicial...');
        await this.seedToFirestore();
        console.log('[DB] Seed inicial concluído.');
      }

      console.log('[DB] Sincronização com Firestore concluída com sucesso.');
    } catch (e) {
      console.error('[DB] Falha ao carregar dados do Firestore:', e);
    }
  }

  /**
   * Seeds all in-memory data to Firestore.
   * Called when the Firestore database is empty on first run.
   */
  public async seedToFirestore() {
    const batch = adminDb.batch();

    for (const u of this.users) {
      batch.set(adminDb.collection('users').doc(u.id), u, { merge: true });
    }
    for (const p of this.processes) {
      batch.set(adminDb.collection('processes').doc(p.id), p, { merge: true });
    }
    for (const m of this.matrices) {
      const { regras, ...matrixData } = m;
      batch.set(adminDb.collection('matrices').doc(m.id), matrixData, { merge: true });
    }
    for (const r of this.requests) {
      batch.set(adminDb.collection('requests').doc(r.id), r, { merge: true });
    }
    for (const log of this.auditLogs) {
      batch.set(adminDb.collection('auditLogs').doc(log.id), log, { merge: true });
    }
    for (const notif of this.notifications) {
      batch.set(adminDb.collection('notifications').doc(notif.id), notif, { merge: true });
    }

    await batch.commit();

    // Persist matrix rules as subcollections (can't go in batch due to size)
    for (const m of this.matrices) {
      await this.syncMatrixRules(m.id, m.regras || []);
    }
  }

  public async syncToFirestore(collection: string, docId: string, data: any) {
    try {
      await adminDb.collection(collection).doc(docId).set(data, { merge: true });
    } catch (e) {
      console.error(`[DB] Firestore sync error (${collection}/${docId}):`, e);
    }
  }

  public async deleteFromFirestore(collection: string, docId: string) {
    try {
      await adminDb.collection(collection).doc(docId).delete();
    } catch (e) {
      console.error(`[DB] Firestore delete error (${collection}/${docId}):`, e);
    }
  }

  /**
   * Sincroniza as regras de uma matriz como subcoleção no Firestore.
   * Removes regras antigas e grava as novas.
   */
  public async syncMatrixRules(matrixId: string, rules: RegraAlcada[]) {
    try {
      const rulesRef = adminDb.collection('matrices').doc(matrixId).collection('rules');
      // Delete all existing rules first
      const existing = await rulesRef.get();
      const batch = adminDb.batch();
      existing.docs.forEach(doc => batch.delete(doc.ref));
      for (const rule of rules) {
        batch.set(rulesRef.doc(rule.id), rule, { merge: true });
      }
      await batch.commit();
    } catch (e) {
      console.error(`[DB] Firestore syncMatrixRules error (matrices/${matrixId}/rules):`, e);
    }
  }

  constructor() {
    this.seed();
  }

  private seed() {
    // 1. Seed Users (SB Saúde structure)
    this.users = [
      {
        id: 'usr-1',
        name: 'Raquel Marimon',
        email: 'raquel.marimon@sbsaude.com.br',
        cargo: 'Analista de Gente e Gestão',
        area: 'Gente e Gestão',
        centroCusto: 'CC-1010 - Recursos Humanos',
        phone: '(11) 98765-4321',
        roles: ['SOLICITANTE'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-2',
        name: 'Haroldo Peon',
        email: 'haroldo.peon@sbsaude.com.br',
        cargo: 'Supervisor de Credenciamento',
        area: 'Credenciamento',
        centroCusto: 'CC-2020 - Rede Credenciada',
        phone: '(11) 98765-1111',
        roles: ['APROVADOR_1'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-3',
        name: 'Janine Sena',
        email: 'janine.sena@sbsaude.com.br',
        cargo: 'Coordenadora de Finanças',
        area: 'Finanças e Controladoria',
        centroCusto: 'CC-3030 - Finanças',
        phone: '(11) 98765-2222',
        roles: ['APROVADOR_1'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-4',
        name: 'Christiane Macedo',
        email: 'christiane.macedo@sbsaude.com.br',
        cargo: 'Gerente de Credenciamento e Núcleo Assistencial',
        area: 'Núcleo Assistencial',
        centroCusto: 'CC-2020 - Rede Credenciada',
        phone: '(11) 98765-3333',
        roles: ['APROVADOR_2'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-5',
        name: 'Dr. Carlos Eduardo',
        email: 'carlos.eduardo@sbsaude.com.br',
        cargo: 'Gerente de COM & MKT',
        area: 'Comunicação e Marketing',
        centroCusto: 'CC-4040 - Marketing',
        phone: '(11) 98765-4444',
        roles: ['APROVADOR_2'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-6',
        name: 'Dra. Mariana Silva',
        email: 'mariana.silva@sbsaude.com.br',
        cargo: 'Diretora de Operações',
        area: 'Diretoria de Operações',
        centroCusto: 'CC-5050 - Operações',
        phone: '(11) 98765-5555',
        roles: ['APROVADOR_3'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-7',
        name: 'Roberto Guimarães',
        email: 'roberto.guimaraes@sbsaude.com.br',
        cargo: 'Diretor Financeiro',
        area: 'Diretoria Financeira',
        centroCusto: 'CC-3030 - Finanças',
        phone: '(11) 98765-6666',
        roles: ['APROVADOR_3'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-8',
        name: 'Janaína Mascarenhas',
        email: 'janaina.mascarenhas@sbsaude.com.br',
        cargo: 'Diretoria Executiva / Conselho',
        area: 'Presidência Executiva',
        centroCusto: 'CC-9090 - Conselho Executivo',
        phone: '(11) 98765-7777',
        roles: ['APROVADOR_4'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-9',
        name: 'Patrícia Mendes',
        email: 'patricia.mendes@sbsaude.com.br',
        cargo: 'Analista de Contas a Pagar / Financeiro',
        area: 'Contas a Pagar',
        centroCusto: 'CC-3030 - Finanças',
        phone: '(11) 98765-8888',
        roles: ['FINANCEIRO'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-10',
        name: 'Fernando Rocha',
        email: 'fernando.rocha@sbsaude.com.br',
        cargo: 'Coordenador de Tesouraria',
        area: 'Tesouraria',
        centroCusto: 'CC-3030 - Finanças',
        phone: '(11) 98765-9999',
        roles: ['TESOURARIA'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
      {
        id: 'usr-11',
        name: 'Vanessa Duarte',
        email: 'vanessa.duarte@sbsaude.com.br',
        cargo: 'Gerente de Governança e SGQ / Admin',
        area: 'Governança e Qualidade',
        centroCusto: 'CC-8080 - Governança SGQ',
        phone: '(11) 98765-0000',
        roles: ['ADMINISTRADOR'],
        status: 'ATIVO',
        authType: 'EMAIL_PASSWORD',
        isEmailVerified: true,
        createdAt: '2026-07-01T08:00:00Z',
        lastLoginAt: '2026-08-27T07:30:00Z',
      },
    ];

    // 2. Seed All Processes from POL-DIR-01
    const rawProcesses: Array<Omit<ProcessItem, 'createdAt' | 'updatedAt'>> = [
      {
        id: 'proc-01',
        code: 'PRC-DEMISSOES-ALTO-RISCO',
        name: 'Demissões de alto risco jurídico ou envolvendo cargos estratégicos',
        description: 'Desligamentos estratégicos ou com potencial de litígio trabalhista relevante',
        natureza: 'RH',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-02',
        code: 'PRC-COMPRAS-TI',
        name: 'Compras de equipamento e outras demandas de tecnologia da informação (TI)',
        description: 'Aquisição de hardware, infraestrutura de servidores e licenças de software corporativo',
        natureza: 'TI',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-03',
        code: 'PRC-PRESTADORES-REDE',
        name: 'Pagamento de prestadores (Rede)',
        description: 'Honorários médicos, clínicas, laboratórios e rede hospitalar credenciada',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-04',
        code: 'PRC-PARTOS-EMERGENCIAIS',
        name: 'Autorização de partos Emergenciais / Eletivos',
        description: 'Procedimentos obstétricos e partos em maternidades parceiras',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-05',
        code: 'PRC-PAGAMENTOS-DIVERSOS-DIR',
        name: 'Autorização de pagamentos diversos (Diretoria)',
        description: 'Despesas extraordinárias e demandas estratégicas corporativas',
        natureza: 'FINANCEIRO',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-06',
        code: 'PRC-CIRURGIA-EMERGENCIAL',
        name: 'Autorização de cirurgia emergencial',
        description: 'Cirurgias urgentes e intervenções hospitalares imediatas',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-07',
        code: 'PRC-ONCO-CRONICOS-ALTA',
        name: 'Procedimentos oncológicos/Crônicos de maior complexidade (acima R$ 2.001,00)',
        description: 'Tratamentos oncológicos contínuos, quimioterapia, imunoterapia e terapias de alto custo',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-08',
        code: 'PRC-CIRURGIAS-JUDICIAIS',
        name: 'Autorização de Cirurgias provenientes de processos judiciais',
        description: 'Cumprimento de liminares e determinações judiciais para cirurgias',
        natureza: 'JURIDICO',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-09',
        code: 'PRC-NIPS-ELETIVAS',
        name: 'Autorização de NIPs eletivas',
        description: 'Demandas da Notificação de Intermediação Preliminar da ANS em caráter eletivo',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-10',
        code: 'PRC-PREPAG-CONSULTAS-EXAMES',
        name: 'Pré pagamentos de consultas e exames eletivo',
        description: 'Adiantamento e pré-pagamento para clínicas e laboratórios de rotina',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-11',
        code: 'PRC-NIP-URGENCIA',
        name: 'Autorização de NIP de urgência',
        description: 'Notificação de Intermediação Preliminar ANS com prazo urgente/crítico',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-12',
        code: 'PRC-PREPAG-NIPEIROS',
        name: 'Pré pagamentos de beneficiários com reclamações reincidentes (Nipeiros)',
        description: 'Liberação assistencial para mitigação de riscos de reincidência perante a ANS',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-13',
        code: 'PRC-REEMBOLSO',
        name: 'Reembolso',
        description: 'Reembolso de despesas médico-hospitalares conforme contrato do plano',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-14',
        code: 'PRC-ACORDOS-JUDICIAIS',
        name: 'Autorização de Acordos Judiciais',
        description: 'Homologação e pagamentos de acordos e conciliações cíveis e assistenciais',
        natureza: 'JURIDICO',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-15',
        code: 'PRC-ANESTESIAS',
        name: 'Autorização de Anestesias',
        description: 'Honorários de equipes anestésicas e cooperativas anestesiológicas',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-16',
        code: 'PRC-ACOES-EXTERNAS-MKT',
        name: 'Ações Externas (Parceiros / Corretores / Beneficiários)',
        description: 'Eventos institucionais externos, stands, relacionamento e premiações',
        natureza: 'MARKETING',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-17',
        code: 'PRC-POS-VENDA',
        name: 'Pagamentos de demandas do Pós Venda',
        description: 'Ressarcimentos e adequações contratuais pós-adesão',
        natureza: 'OPERACIONAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-18',
        code: 'PRC-INFLUENCER-MIDIA',
        name: 'Influencer Mídia',
        description: 'Contratação de influenciadores e campanhas de alcance em mídias sociais',
        natureza: 'MARKETING',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-19',
        code: 'PRC-PROC-AMB-ACIMA-2K',
        name: 'Procedimentos ambulatoriais eletivos (acima de R$ 2.001,00)',
        description: 'Consultas especializadas e procedimentos ambulatoriais de maior custo',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-20',
        code: 'PRC-CIRURGIAS-MAIOR-COMPLEX',
        name: 'Cirurgias de maior complexidade (acima R$ 2.001,00)',
        description: 'Intervenções cirúrgicas de médio e grande porte',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-21',
        code: 'PRC-PROC-AMB-ATE-2K',
        name: 'Procedimentos ambulatoriais eletivos (até R$ 2.000,00)',
        description: 'Exames e consultas de rotina em clínicas credenciadas',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-22',
        code: 'PRC-CIRURGIAS-MENOR-COMPLEX',
        name: 'Cirurgias de menor complexidade (até R$ 2.000,00)',
        description: 'Pequenas cirurgias e procedimentos de curta permanência',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-23',
        code: 'PRC-ONCO-CRONICOS-ATE-2K',
        name: 'Procedimentos oncológicos / Crônicos de menor complexidade (até R$ 2.000,00)',
        description: 'Medicamentos orais e aplicações de suporte ambulatorial oncológico',
        natureza: 'ASSISTENCIAL',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-24',
        code: 'PRC-CAMPANHAS-INTERNAS',
        name: 'Campanhas Internas',
        description: 'Comunicação interna, endomarketing e eventos com colaboradores',
        natureza: 'MARKETING',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-25',
        code: 'PRC-PROJETO-SOCIAL',
        name: 'Projeto Social "Alguém Que Se Importa"',
        description: 'Iniciativas sociais e ações humanitárias institucionais SB Saúde',
        natureza: 'MARKETING',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-26',
        code: 'PRC-PAGAMENTOS-DIVERSOS-FIN',
        name: 'Autorização de pagamentos diversos (Finanças)',
        description: 'Taxas, emolumentos, serviços cartorários e despesas operacionais rotineiras',
        natureza: 'FINANCEIRO',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-27',
        code: 'PRC-DEMISSOES-BAIXO-RISCO',
        name: 'Demissões sem justa causa de baixo risco jurídico',
        description: 'Rescisões contratuais padrão de colaboradores operacionais',
        natureza: 'RH',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: false,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-28',
        code: 'PRC-ACORDOS-TRABALHISTAS',
        name: 'Acordos trabalhistas até um valor pré-definido',
        description: 'Transações e acordos em câmaras de conciliação trabalhista',
        natureza: 'JURIDICO',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: true,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-29',
        code: 'PRC-ACOES-INTERNAS-EVENTUAIS',
        name: 'Ações Internas Eventuais',
        description: 'Comemorações, premiações de equipes e ações de engajamento',
        natureza: 'MARKETING',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-30',
        code: 'PRC-FORNECEDORES-ADM-RH',
        name: 'Contratação de fornecedores para atender as demandas administrativas e recursos humanos',
        description: 'Serviços de limpeza, manutenção predial, suprimentos e apoio operacional',
        natureza: 'ADMINISTRATIVO',
        riscoPadrao: 'MEDIO',
        requerJustificativaTecnica: false,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-31',
        code: 'PRC-TREINAMENTOS-RH',
        name: 'Contratação de treinamentos e consultorias de RH dentro do orçamento',
        description: 'Capacitações técnicas, cursos e consultorias especializadas',
        natureza: 'RH',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: true,
        ativo: true,
      },
      {
        id: 'proc-32',
        code: 'PRC-PROMOCOES-SALARIAIS',
        name: 'Promoções e movimentações internas com impacto salarial até determinado limite (ex.: até 10% de aumento)',
        description: 'Ajustes no plano de cargos e salários e promoções de mérito',
        natureza: 'RH',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: true,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-33',
        code: 'PRC-TRAFEGO-PAGO',
        name: 'Tráfego Pago (Instagram)',
        description: 'Investimento em anúncios digitais, meta ads e campanhas de captação',
        natureza: 'MARKETING',
        riscoPadrao: 'ALTO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
      {
        id: 'proc-34',
        code: 'PRC-BENEFICIOS-NAO-OBRIGATORIOS',
        name: 'Benefícios não obrigatórios dentro de orçamento aprovado',
        description: 'Subsídios, convênios e benefícios opcionais para o quadro funcional',
        natureza: 'RH',
        riscoPadrao: 'BAIXO',
        requerJustificativaTecnica: false,
        permiteParcelamento: false,
        ativo: true,
      },
    ];

    this.processes = rawProcesses.map((p) => ({
      ...p,
      createdAt: '2026-07-07T09:00:00Z',
      updatedAt: '2026-07-07T09:00:00Z',
    }));

    // 3. Seed Matrix POL-DIR-01 Rev. 00
    const rules: RegraAlcada[] = [
      {
        id: 'rule-01',
        matrizId: 'mtz-00',
        processoId: 'proc-01',
        processoNome: 'Demissões de alto risco jurídico ou envolvendo cargos estratégicos',
        risco: 'ALTO',
        alçadaPorEvento: 0,
        tetoMensal: 0,
        cargosHabilitados1: ['Diretoria de Operações'],
        cargosHabilitados2: ['Diretoria Financeira'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-02',
        matrizId: 'mtz-00',
        processoId: 'proc-02',
        processoNome: 'Compras de equipamento e outras demandas de tecnologia da informação (TI)',
        risco: 'BAIXO',
        alçadaPorEvento: 0,
        tetoMensal: 0,
        cargosHabilitados1: ['DIRETORIA FINANCEIRA', 'Diretor Financeiro'],
        nivelMaximoRequerido: 1,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-03',
        matrizId: 'mtz-00',
        processoId: 'proc-03',
        processoNome: 'Pagamento de prestadores (Rede)',
        risco: 'ALTO',
        alçadaPorEvento: 150000,
        tetoMensal: 500000,
        cargosHabilitados1: ['Gerente Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-04',
        matrizId: 'mtz-00',
        processoId: 'proc-04',
        processoNome: 'Autorização de partos Emergenciais / Eletivos',
        risco: 'ALTO',
        alçadaPorEvento: 25000,
        tetoMensal: 70000,
        cargosHabilitados1: ['Acolhimento a Gestantes', 'Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Núcleo Assistencial', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados4: ['Diretoria Financeira', 'Diretoria Executiva / Conselho'],
        nivelMaximoRequerido: 4,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-05',
        matrizId: 'mtz-00',
        processoId: 'proc-05',
        processoNome: 'Autorização de pagamentos diversos (Diretoria)',
        risco: 'ALTO',
        alçadaPorEvento: 25000,
        tetoMensal: 100000,
        cargosHabilitados1: ['Diretora de Operações', 'Diretoria de Operações'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-06',
        matrizId: 'mtz-00',
        processoId: 'proc-06',
        processoNome: 'Autorização de cirurgia emergencial',
        risco: 'ALTO',
        alçadaPorEvento: 20000,
        tetoMensal: 80000,
        cargosHabilitados1: ['Gerente Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-07',
        matrizId: 'mtz-00',
        processoId: 'proc-07',
        processoNome: 'Procedimentos oncológicos/Crônicos de maior complexidade (acima R$ 2.001,00)',
        risco: 'ALTO',
        alçadaPorEvento: 20000,
        tetoMensal: 80000,
        cargosHabilitados1: ['Gerência de Núcleo Assistencial', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-08',
        matrizId: 'mtz-00',
        processoId: 'proc-08',
        processoNome: 'Autorização de Cirurgias provenientes de processos judiciais',
        risco: 'ALTO',
        alçadaPorEvento: 20000,
        tetoMensal: 40000,
        cargosHabilitados1: ['Coordenador de Núcleo Regulatório', 'Supervisor de Credenciamento'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-09',
        matrizId: 'mtz-00',
        processoId: 'proc-09',
        processoNome: 'Autorização de NIPs eletivas',
        risco: 'ALTO',
        alçadaPorEvento: 12500,
        tetoMensal: 50000,
        cargosHabilitados1: ['Coordenador Núcleo de Experiência do Beneficiário', 'Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-10',
        matrizId: 'mtz-00',
        processoId: 'proc-10',
        processoNome: 'Pré pagamentos de consultas e exames eletivo',
        risco: 'MEDIO',
        alçadaPorEvento: 13000,
        tetoMensal: 52000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-11',
        matrizId: 'mtz-00',
        processoId: 'proc-11',
        processoNome: 'Autorização de NIP de urgência',
        risco: 'ALTO',
        alçadaPorEvento: 10000,
        tetoMensal: 40000,
        cargosHabilitados1: ['Coordenador Núcleo de Experiência do Beneficiário', 'Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-12',
        matrizId: 'mtz-00',
        processoId: 'proc-12',
        processoNome: 'Pré pagamentos de beneficiários com reclamações reincidentes (Nipeiros)',
        risco: 'ALTO',
        alçadaPorEvento: 5000,
        tetoMensal: 20000,
        cargosHabilitados1: ['Gerente da Qualidade', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-13',
        matrizId: 'mtz-00',
        processoId: 'proc-13',
        processoNome: 'Reembolso',
        risco: 'MEDIO',
        alçadaPorEvento: 5000,
        tetoMensal: 20000,
        cargosHabilitados1: ['Gerência de Núcleo Assistencial', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-14',
        matrizId: 'mtz-00',
        processoId: 'proc-14',
        processoNome: 'Autorização de Acordos Judiciais',
        risco: 'ALTO',
        alçadaPorEvento: 5000,
        tetoMensal: 20000,
        cargosHabilitados1: ['Coordenador de Núcleo Regulatório', 'Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-15',
        matrizId: 'mtz-00',
        processoId: 'proc-15',
        processoNome: 'Autorização de Anestesias',
        risco: 'MEDIO',
        alçadaPorEvento: 3000,
        tetoMensal: 12000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-16',
        matrizId: 'mtz-00',
        processoId: 'proc-16',
        processoNome: 'Ações Externas (Parceiros / Corretores / Beneficiários)',
        risco: 'ALTO',
        alçadaPorEvento: 3000,
        tetoMensal: 3000,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-17',
        matrizId: 'mtz-00',
        processoId: 'proc-17',
        processoNome: 'Pagamentos de demandas do Pós Venda',
        risco: 'MEDIO',
        alçadaPorEvento: 2500,
        tetoMensal: 10000,
        cargosHabilitados1: ['Coordenadora Comercial', 'Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-18',
        matrizId: 'mtz-00',
        processoId: 'proc-18',
        processoNome: 'Influencer Mídia',
        risco: 'MEDIO',
        alçadaPorEvento: 2500,
        tetoMensal: 2500,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-19',
        matrizId: 'mtz-00',
        processoId: 'proc-19',
        processoNome: 'Procedimentos ambulatoriais eletivos (acima de R$ 2.001,00)',
        risco: 'BAIXO',
        alçadaPorEvento: 2001,
        tetoMensal: 60000,
        cargosHabilitados1: ['Gerência de Núcleo Assistencial', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-20',
        matrizId: 'mtz-00',
        processoId: 'proc-20',
        processoNome: 'Cirurgias de maior complexidade (acima R$ 2.001,00)',
        risco: 'ALTO',
        alçadaPorEvento: 2001,
        tetoMensal: 50000,
        cargosHabilitados1: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-21',
        matrizId: 'mtz-00',
        processoId: 'proc-21',
        processoNome: 'Procedimentos ambulatoriais eletivos (até R$ 2.000,00)',
        risco: 'BAIXO',
        alçadaPorEvento: 2000,
        tetoMensal: 8000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-22',
        matrizId: 'mtz-00',
        processoId: 'proc-22',
        processoNome: 'Cirurgias de menor complexidade (até R$ 2.000,00)',
        risco: 'MEDIO',
        alçadaPorEvento: 2000,
        tetoMensal: 8000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-23',
        matrizId: 'mtz-00',
        processoId: 'proc-23',
        processoNome: 'Procedimentos oncológicos / Crônicos de menor complexidade (até R$ 2.000,00)',
        risco: 'ALTO',
        alçadaPorEvento: 2000,
        tetoMensal: 8000,
        cargosHabilitados1: ['Supervisor de Credenciamento'],
        cargosHabilitados2: ['Gerência de Credenciamento', 'Gerente de Credenciamento e Núcleo Assistencial'],
        cargosHabilitados3: ['Diretoria de Operações', 'Diretora de Operações'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-24',
        matrizId: 'mtz-00',
        processoId: 'proc-24',
        processoNome: 'Campanhas Internas',
        risco: 'BAIXO',
        alçadaPorEvento: 2000,
        tetoMensal: 2000,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-25',
        matrizId: 'mtz-00',
        processoId: 'proc-25',
        processoNome: 'Projeto Social "Alguém Que Se Importa"',
        risco: 'BAIXO',
        alçadaPorEvento: 2000,
        tetoMensal: 2000,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-26',
        matrizId: 'mtz-00',
        processoId: 'proc-26',
        processoNome: 'Autorização de pagamentos diversos (Finanças)',
        risco: 'MEDIO',
        alçadaPorEvento: 2000,
        tetoMensal: 10000,
        cargosHabilitados1: ['Coordenadora de Finanças'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-27',
        matrizId: 'mtz-00',
        processoId: 'proc-27',
        processoNome: 'Demissões sem justa causa de baixo risco jurídico',
        risco: 'ALTO',
        alçadaPorEvento: 1500,
        tetoMensal: 6000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-28',
        matrizId: 'mtz-00',
        processoId: 'proc-28',
        processoNome: 'Acordos trabalhistas até um valor pré-definido',
        risco: 'MEDIO',
        alçadaPorEvento: 1500,
        tetoMensal: 6000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-29',
        matrizId: 'mtz-00',
        processoId: 'proc-29',
        processoNome: 'Ações Internas Eventuais',
        risco: 'ALTO',
        alçadaPorEvento: 1000,
        tetoMensal: 1000,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-30',
        matrizId: 'mtz-00',
        processoId: 'proc-30',
        processoNome: 'Contratação de fornecedores para atender as demandas administrativas e recursos humanos',
        risco: 'MEDIO',
        alçadaPorEvento: 750,
        tetoMensal: 3000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-31',
        matrizId: 'mtz-00',
        processoId: 'proc-31',
        processoNome: 'Contratação de treinamentos e consultorias de RH dentro do orçamento',
        risco: 'BAIXO',
        alçadaPorEvento: 600,
        tetoMensal: 2400,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-32',
        matrizId: 'mtz-00',
        processoId: 'proc-32',
        processoNome: 'Promoções e movimentações internas com impacto salarial até determinado limite (ex.: até 10% de aumento)',
        risco: 'BAIXO',
        alçadaPorEvento: 500,
        tetoMensal: 2000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria de Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: true,
        ativo: true,
      },
      {
        id: 'rule-33',
        matrizId: 'mtz-00',
        processoId: 'proc-33',
        processoNome: 'Tráfego Pago (Instagram)',
        risco: 'ALTO',
        alçadaPorEvento: 500,
        tetoMensal: 500,
        cargosHabilitados1: ['Gerente de COM & MKT'],
        cargosHabilitados2: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 2,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
      {
        id: 'rule-34',
        matrizId: 'mtz-00',
        processoId: 'proc-34',
        processoNome: 'Benefícios não obrigatórios dentro de orçamento aprovado',
        risco: 'BAIXO',
        alçadaPorEvento: 250,
        tetoMensal: 1000,
        cargosHabilitados1: ['Coord. Gente e Gestão', 'Analista de Gente e Gestão'],
        cargosHabilitados2: ['Diretoria De Operações', 'Diretora de Operações'],
        cargosHabilitados3: ['Diretoria Financeira', 'Diretor Financeiro'],
        nivelMaximoRequerido: 3,
        requerJustificativaSeAcimaLimite: false,
        ativo: true,
      },
    ];

    this.matrices = [
      {
        id: 'mtz-00',
        codigo: 'POL-DIR-01',
        versao: 'Rev. 00',
        titulo: 'Política de Alçada e Delegação de Autoridade (Vigência 2026-2028)',
        status: 'VIGENTE',
        vigenciaInicio: '2026-07-07',
        vigenciaFim: '2028-07-07',
        elaboracao: 'Raquel Marimon / Janine Sena',
        revisao: 'Christiane Macedo / Haroldo Peon',
        aprovacao: 'Janaína Mascarenhas',
        publicadoPor: 'Vanessa Duarte (SGQ)',
        publicadoEm: '2026-07-07T10:00:00Z',
        historicoAlteracoes: 'Emissão Inicial aprovada pela Diretoria Executiva conforme RN ANS nº 518/2022 e ISO 9001:2015.',
        regras: rules,
        createdAt: '2026-07-07T08:00:00Z',
        updatedAt: '2026-07-07T10:00:00Z',
      },
    ];

    // 4. Seed Realistic Initial Requests demonstrating all workflows
    this.requests = [
      // 1. Within 1st tier (Anestesias - Haroldo Peon approving)
      {
        id: 'req-0001',
        numero: 'FIN-ALC-0001/2026',
        sequencial: 1,
        ano: 2026,
        dataSolicitacao: '2026-08-20',
        areaSolicitante: 'Credenciamento',
        centroCusto: 'CC-2020 - Rede Credenciada',
        solicitanteId: 'usr-1',
        solicitanteNome: 'Raquel Marimon',
        solicitanteCargo: 'Analista de Gente e Gestão',
        solicitanteEmail: 'raquel.marimon@sbsaude.com.br',
        processoId: 'proc-15',
        processoNome: 'Autorização de Anestesias',
        processoContratoNumero: 'CTR-ANES-2026/88',
        fornecedorFavorecido: 'COOPANEST - Cooperativa dos Anestesiologistas de SP',
        cpfCnpj: '44.123.456/0001-90',
        objetoDespesa: 'Honorários de serviços de anestesia de plantão cirúrgico semanal',
        valorTotal: 2800.0,
        natureza: 'EVENTUAL',
        formaPagamento: 'TED_PIX',
        parcelamento: false,
        dataVencimento: '2026-09-08',
        diasUteisAteVencimento: 8,
        alertaVencimentoProximo: false,
        rubricaOrcamentaria: '3.1.02.05 - Honorários Médicos Especializados',
        previstoNoOrcamento: true,
        saldoDisponivel: true,
        dadosBancarios: {
          banco: '341 - Itaú Unibanco',
          agencia: '0982',
          contaCorrente: '44120-9',
          chavePix: '44.123.456/0001-90',
          titular: 'COOPANEST SP',
        },
        faixaValorCalculada: 'ATE_5K',
        faixaValorLabel: 'até R$ 5 mil',
        nivelRisco: 'MEDIO',
        criteriosRisco: {
          assistencial: true,
          regulatorioAns: false,
          financeiro: false,
          reputacional: false,
        },
        alcadaAplicavelMaxima: 1,
        alcadaAplicavelLabel: '1ª (Coord./Superv.)',
        matrizAlcadaId: 'mtz-00',
        matrizAlcadaCodigo: 'POL-DIR-01',
        matrizAlcadaVersao: 'Rev. 00',
        regraAlcadaId: 'rule-15',
        tetoMensalProcesso: 12000,
        tetoMensalAcumuladoAtual: 5600,
        tetoMensalEstourado: false,
        declaracaoSegregacaoFuncoes: true,
        declaracaoRegraQuatroOlhos: true,
        declaracaoProibicaoFracionamento: true,
        declaracaoAusenciaConflito: true,
        declaracaoAprovacaoPreviaCompromisso: true,
        status: 'AGUARDANDO_1_ALCADA',
        etapaAtualNivel: 1,
        cadeiaAprovacao: [
          {
            id: 'apr-001-1',
            solicitacaoId: 'req-0001',
            nivel: 1,
            nivelLabel: '1ª Alçada - Coordenação/Supervisão',
            cargoExigido: 'Supervisor de Credenciamento',
            areaExigida: 'Credenciamento',
            aprovadorDesignadoId: 'usr-2',
            aprovadorDesignadoNome: 'Haroldo Peon',
            status: 'PENDENTE',
            declaracaoConflitoInteresse: false,
            dataEntrada: '2026-08-20T09:00:00Z',
          },
        ],
        documentos: [
          {
            id: 'doc-001-1',
            solicitacaoId: 'req-0001',
            tipo: 'NF_FATURA',
            nomeArquivo: 'NF-10492-COOPANEST.pdf',
            tamanhoBytes: 412000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-20T08:50:00Z',
          },
          {
            id: 'doc-001-2',
            solicitacaoId: 'req-0001',
            tipo: 'BOLETO',
            nomeArquivo: 'Boleto_Itau_Anestesia.pdf',
            tamanhoBytes: 250000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-20T08:52:00Z',
          },
        ],
        createdAt: '2026-08-20T08:50:00Z',
        updatedAt: '2026-08-20T09:00:00Z',
      },

      // 2. Requiring 2nd tier escalation (Procedimentos ambulatoriais acima de 2k - Christiane -> Dra. Mariana)
      {
        id: 'req-0002',
        numero: 'FIN-ALC-0002/2026',
        sequencial: 2,
        ano: 2026,
        dataSolicitacao: '2026-08-21',
        areaSolicitante: 'Núcleo Assistencial',
        centroCusto: 'CC-2020 - Rede Credenciada',
        solicitanteId: 'usr-1',
        solicitanteNome: 'Raquel Marimon',
        solicitanteCargo: 'Analista de Gente e Gestão',
        solicitanteEmail: 'raquel.marimon@sbsaude.com.br',
        processoId: 'proc-19',
        processoNome: 'Procedimentos ambulatoriais eletivos (acima de R$ 2.001,00)',
        processoContratoNumero: 'CTR-AMB-2025/110',
        fornecedorFavorecido: 'Centro Diagnóstico Paulistano Ltda',
        cpfCnpj: '12.345.678/0001-22',
        objetoDespesa: 'Lote de exames de ressonância magnética de alto campo e cintilografia',
        valorTotal: 18500.0,
        natureza: 'EVENTUAL',
        formaPagamento: 'BOLETO',
        parcelamento: false,
        dataVencimento: '2026-09-02',
        diasUteisAteVencimento: 4,
        alertaVencimentoProximo: true, // < 5 dias úteis!
        rubricaOrcamentaria: '3.1.01.02 - Diagnósticos por Imagem Especializados',
        previstoNoOrcamento: true,
        saldoDisponivel: true,
        dadosBancarios: {
          banco: '237 - Bradesco',
          agencia: '3200',
          contaCorrente: '98765-4',
          titular: 'Centro Diagnóstico Paulistano Ltda',
        },
        faixaValorCalculada: 'DE_5K_A_20K',
        faixaValorLabel: 'R$ 5–20 mil',
        nivelRisco: 'BAIXO',
        criteriosRisco: {
          assistencial: true,
          regulatorioAns: false,
          financeiro: false,
          reputacional: false,
        },
        alcadaAplicavelMaxima: 2,
        alcadaAplicavelLabel: '2ª (Gerência)',
        matrizAlcadaId: 'mtz-00',
        matrizAlcadaCodigo: 'POL-DIR-01',
        matrizAlcadaVersao: 'Rev. 00',
        regraAlcadaId: 'rule-19',
        tetoMensalProcesso: 60000,
        tetoMensalAcumuladoAtual: 42000,
        tetoMensalEstourado: false,
        declaracaoSegregacaoFuncoes: true,
        declaracaoRegraQuatroOlhos: true,
        declaracaoProibicaoFracionamento: true,
        declaracaoAusenciaConflito: true,
        declaracaoAprovacaoPreviaCompromisso: true,
        status: 'AGUARDANDO_2_ALCADA',
        etapaAtualNivel: 2,
        cadeiaAprovacao: [
          {
            id: 'apr-002-1',
            solicitacaoId: 'req-0002',
            nivel: 1,
            nivelLabel: '1ª Alçada - Gerência de Núcleo Assistencial',
            cargoExigido: 'Gerente de Credenciamento e Núcleo Assistencial',
            aprovadorDesignadoId: 'usr-4',
            aprovadorDesignadoNome: 'Christiane Macedo',
            aprovadorRealId: 'usr-4',
            aprovadorRealNome: 'Christiane Macedo',
            aprovadorRealCargo: 'Gerente de Credenciamento e Núcleo Assistencial',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'Conferido relatório de exames realizados. Custo per capita alinhado à tabela negociada.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-21T09:00:00Z',
            dataDecisao: '2026-08-22T14:10:00Z',
            ipAssinatura: '192.168.10.45',
          },
          {
            id: 'apr-002-2',
            solicitacaoId: 'req-0002',
            nivel: 2,
            nivelLabel: '2ª Alçada - Diretoria de Operações',
            cargoExigido: 'Diretora de Operações',
            aprovadorDesignadoId: 'usr-6',
            aprovadorDesignadoNome: 'Dra. Mariana Silva',
            status: 'PENDENTE',
            declaracaoConflitoInteresse: false,
            dataEntrada: '2026-08-22T14:10:00Z',
          },
        ],
        documentos: [
          {
            id: 'doc-002-1',
            solicitacaoId: 'req-0002',
            tipo: 'NF_FATURA',
            nomeArquivo: 'NF-CDP-99201.pdf',
            tamanhoBytes: 540000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: 'b5d4045c3f466fa91fe2cc6abe79232a1a57cdf104f7a26e716e0a1e2789df78',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-21T08:50:00Z',
          },
          {
            id: 'doc-002-2',
            solicitacaoId: 'req-0002',
            tipo: 'CONTRATO',
            nomeArquivo: 'Contrato_CDP_2025_Assinado.pdf',
            tamanhoBytes: 1250000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: '7bc32f146522c0d8f0ff36edcdb5d956f4d548fb2c4e2098e94a8bc370cf99c3',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-21T08:55:00Z',
          },
        ],
        createdAt: '2026-08-21T08:50:00Z',
        updatedAt: '2026-08-22T14:10:00Z',
      },

      // 3. Requiring 3rd tier escalation (Pagamento Prestadores Rede R$ 180.000,00 - Acima de 150k alçada vai até Diretoria Financeira)
      {
        id: 'req-0003',
        numero: 'FIN-ALC-0003/2026',
        sequencial: 3,
        ano: 2026,
        dataSolicitacao: '2026-08-22',
        areaSolicitante: 'Credenciamento',
        centroCusto: 'CC-2020 - Rede Credenciada',
        solicitanteId: 'usr-1',
        solicitanteNome: 'Raquel Marimon',
        solicitanteCargo: 'Analista de Gente e Gestão',
        solicitanteEmail: 'raquel.marimon@sbsaude.com.br',
        processoId: 'proc-03',
        processoNome: 'Pagamento de prestadores (Rede)',
        processoContratoNumero: 'CTR-HOSP-2024/09',
        fornecedorFavorecido: 'Hospital Santa Bárbara de São Paulo S/A',
        cpfCnpj: '01.999.888/0001-77',
        objetoDespesa: 'Fechamento de faturamento mensal de internações clínicas e UTI - Competência Julho/2026',
        valorTotal: 180000.0,
        natureza: 'RECORRENTE',
        formaPagamento: 'TED_PIX',
        parcelamento: false,
        dataVencimento: '2026-09-10',
        diasUteisAteVencimento: 10,
        alertaVencimentoProximo: false,
        rubricaOrcamentaria: '3.1.03.01 - Despesas Hospitalares Rede Própria/Credenciada',
        previstoNoOrcamento: true,
        saldoDisponivel: true,
        dadosBancarios: {
          banco: '001 - Banco do Brasil',
          agencia: '1820',
          contaCorrente: '77889-0',
          chavePix: '01.999.888/0001-77',
          titular: 'Hospital Santa Bárbara de São Paulo S/A',
        },
        faixaValorCalculada: 'ACIMA_100K',
        faixaValorLabel: 'acima de R$ 100 mil',
        nivelRisco: 'ALTO',
        criteriosRisco: {
          assistencial: true,
          regulatorioAns: true,
          financeiro: true,
          reputacional: false,
        },
        alcadaAplicavelMaxima: 3,
        alcadaAplicavelLabel: '3ª (Diretoria)',
        matrizAlcadaId: 'mtz-00',
        matrizAlcadaCodigo: 'POL-DIR-01',
        matrizAlcadaVersao: 'Rev. 00',
        regraAlcadaId: 'rule-03',
        tetoMensalProcesso: 500000,
        tetoMensalAcumuladoAtual: 340000,
        tetoMensalEstourado: false,
        declaracaoSegregacaoFuncoes: true,
        declaracaoRegraQuatroOlhos: true,
        declaracaoProibicaoFracionamento: true,
        declaracaoAusenciaConflito: true,
        declaracaoAprovacaoPreviaCompromisso: true,
        justificativaTecnica: {
          necessidadeContexto: 'Fechamento de faturamento consolidado de 42 internações de alta complexidade em UTI credenciada.',
          areaDemandante: 'Credenciamento e Auditoria Médica Hospitalar',
          fundamentacaoTecnicaNormas: 'RN ANS nº 518/2022 e contrato de credenciamento hospitalar com tabela TUSS/CBHPM auditada.',
          dadosObjetivos: 'Auditoria in loco realizada pela equipe médica com glosas de 4,2% já deduzidas da fatura bruta.',
          alternativasAvaliadas: 'Valores conferidos frente à tabela contratada sem divergências.',
          motivoEscolhaFornecedor: 'Hospital polo de referência da operadora na capital para cardiologia e neurologia.',
          impactoAssistencial: 'Garantia de continuidade do atendimento de urgência e emergência aos 35.000 beneficiários da região.',
          impactoRegulatorio: 'Prevenção de NIPs assistenciais e preservação dos indicadores de solvência IDSS.',
          impactoFinanceiro: 'Dentro da projeção atuarial da sinistralidade médica do trimestre.',
          riscosNaoExecucao: 'Descredenciamento imediato por inadimplência e suspensão de leitos de UTI.',
        },
        status: 'AGUARDANDO_3_ALCADA',
        etapaAtualNivel: 3,
        cadeiaAprovacao: [
          {
            id: 'apr-003-1',
            solicitacaoId: 'req-0003',
            nivel: 1,
            nivelLabel: '1ª Alçada - Gerente de Credenciamento',
            cargoExigido: 'Gerente de Credenciamento e Núcleo Assistencial',
            aprovadorDesignadoId: 'usr-4',
            aprovadorDesignadoNome: 'Christiane Macedo',
            aprovadorRealId: 'usr-4',
            aprovadorRealNome: 'Christiane Macedo',
            aprovadorRealCargo: 'Gerente de Credenciamento e Núcleo Assistencial',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'Faturamento auditado clinicamente com 100% de conferência dos prontuários.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-22T09:00:00Z',
            dataDecisao: '2026-08-22T11:00:00Z',
            ipAssinatura: '192.168.10.45',
          },
          {
            id: 'apr-003-2',
            solicitacaoId: 'req-0003',
            nivel: 2,
            nivelLabel: '2ª Alçada - Diretora de Operações',
            cargoExigido: 'Diretora de Operações',
            aprovadorDesignadoId: 'usr-6',
            aprovadorDesignadoNome: 'Dra. Mariana Silva',
            aprovadorRealId: 'usr-6',
            aprovadorRealNome: 'Dra. Mariana Silva',
            aprovadorRealCargo: 'Diretora de Operações',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'Aprovado conforme sinistralidade prevista e metas assistenciais cumpridas.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-22T11:00:00Z',
            dataDecisao: '2026-08-23T15:30:00Z',
            ipAssinatura: '192.168.10.88',
          },
          {
            id: 'apr-003-3',
            solicitacaoId: 'req-0003',
            nivel: 3,
            nivelLabel: '3ª Alçada - Diretoria Financeira',
            cargoExigido: 'Diretor Financeiro',
            aprovadorDesignadoId: 'usr-7',
            aprovadorDesignadoNome: 'Roberto Guimarães',
            status: 'PENDENTE',
            declaracaoConflitoInteresse: false,
            dataEntrada: '2026-08-23T15:30:00Z',
          },
        ],
        documentos: [
          {
            id: 'doc-003-1',
            solicitacaoId: 'req-0003',
            tipo: 'NF_FATURA',
            nomeArquivo: 'NF_Eletronica_SantaBarbara_180k.pdf',
            tamanhoBytes: 890000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-22T08:30:00Z',
          },
          {
            id: 'doc-003-2',
            solicitacaoId: 'req-0003',
            tipo: 'PARECER_TECNICO',
            nomeArquivo: 'Relatorio_Auditoria_Medica_Internacoes.pdf',
            tamanhoBytes: 1540000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: '38b97d7c67bfefc5c8397a61d15db31c94becc81395568ef8a571c500ab1432f',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-22T08:35:00Z',
          },
        ],
        createdAt: '2026-08-22T08:30:00Z',
        updatedAt: '2026-08-23T15:30:00Z',
      },

      // 4. Requiring 4th tier escalation (Partos Emergenciais R$ 35.000,00 - Acima de 25k requer Diretoria Executiva/Conselho)
      {
        id: 'req-0004',
        numero: 'FIN-ALC-0004/2026',
        sequencial: 4,
        ano: 2026,
        dataSolicitacao: '2026-08-23',
        areaSolicitante: 'Núcleo Assistencial',
        centroCusto: 'CC-2020 - Rede Credenciada',
        solicitanteId: 'usr-1',
        solicitanteNome: 'Raquel Marimon',
        solicitanteCargo: 'Analista de Gente e Gestão',
        solicitanteEmail: 'raquel.marimon@sbsaude.com.br',
        processoId: 'proc-04',
        processoNome: 'Autorização de partos Emergenciais / Eletivos',
        processoContratoNumero: 'CTR-MAT-2026/04',
        fornecedorFavorecido: 'Maternidade e Hospital da Criança Vida Ltda',
        cpfCnpj: '08.765.432/0001-11',
        objetoDespesa: 'Pacote obstétrico de urgência de alto risco com UTI neonatal',
        valorTotal: 35000.0,
        natureza: 'EVENTUAL',
        formaPagamento: 'BOLETO',
        parcelamento: false,
        dataVencimento: '2026-09-15',
        diasUteisAteVencimento: 13,
        alertaVencimentoProximo: false,
        rubricaOrcamentaria: '3.1.04.01 - Procedimentos Obstétricos e Neonatais',
        previstoNoOrcamento: true,
        saldoDisponivel: true,
        dadosBancarios: {
          banco: '033 - Santander',
          agencia: '4012',
          contaCorrente: '1300892-1',
          titular: 'Maternidade e Hospital da Criança Vida Ltda',
        },
        faixaValorCalculada: 'DE_20K_A_50K',
        faixaValorLabel: 'R$ 20–50 mil',
        nivelRisco: 'ALTO',
        criteriosRisco: {
          assistencial: true,
          regulatorioAns: true,
          financeiro: false,
          reputacional: true,
        },
        alcadaAplicavelMaxima: 4,
        alcadaAplicavelLabel: '4ª (Diretoria Executiva/Conselho)',
        matrizAlcadaId: 'mtz-00',
        matrizAlcadaCodigo: 'POL-DIR-01',
        matrizAlcadaVersao: 'Rev. 00',
        regraAlcadaId: 'rule-04',
        tetoMensalProcesso: 70000,
        tetoMensalAcumuladoAtual: 45000,
        tetoMensalEstourado: false,
        declaracaoSegregacaoFuncoes: true,
        declaracaoRegraQuatroOlhos: true,
        declaracaoProibicaoFracionamento: true,
        declaracaoAusenciaConflito: true,
        declaracaoAprovacaoPreviaCompromisso: true,
        justificativaTecnica: {
          necessidadeContexto: 'Parto gemelar prematuro de 29 semanas em regime de urgência absoluta.',
          areaDemandante: 'Núcleo Assistencial e Programa Acolhimento a Gestantes',
          fundamentacaoTecnicaNormas: 'Diretrizes Clínicas ANS RN nº 518/2022 e Protocolo de Urgência Materno-Infantil.',
          dadosObjetivos: 'Escore de Apgar crítico com indicação imediata de incubadora e suporte ventilatório.',
          alternativasAvaliadas: 'Rede própria sem leito neonatal disponível no momento da internação.',
          motivoEscolhaFornecedor: 'Única maternidade com UTI neonatal nível 3 disponível em raio de 15km.',
          impactoAssistencial: 'Salvaguarda da vida da parturiente e dos recém-nascidos.',
          impactoRegulatorio: 'Evita infração regulatória grave por desassistência.',
          impactoFinanceiro: 'Custo assistencial de urgência justificado.',
          riscosNaoExecucao: 'Óbito fetal/materno e passivo cível/criminal imediato.',
        },
        status: 'AGUARDANDO_4_ALCADA',
        etapaAtualNivel: 4,
        cadeiaAprovacao: [
          {
            id: 'apr-004-1',
            solicitacaoId: 'req-0004',
            nivel: 1,
            nivelLabel: '1ª Alçada - Acolhimento a Gestantes',
            cargoExigido: 'Supervisor de Credenciamento',
            aprovadorDesignadoId: 'usr-2',
            aprovadorDesignadoNome: 'Haroldo Peon',
            aprovadorRealId: 'usr-2',
            aprovadorRealNome: 'Haroldo Peon',
            aprovadorRealCargo: 'Supervisor de Credenciamento',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'Elegibilidade confirmada e indicação médica respaldada pelo obstetra de plantão.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-23T10:00:00Z',
            dataDecisao: '2026-08-23T10:30:00Z',
          },
          {
            id: 'apr-004-2',
            solicitacaoId: 'req-0004',
            nivel: 2,
            nivelLabel: '2ª Alçada - Gerência de Núcleo Assistencial',
            cargoExigido: 'Gerente de Credenciamento e Núcleo Assistencial',
            aprovadorDesignadoId: 'usr-4',
            aprovadorDesignadoNome: 'Christiane Macedo',
            aprovadorRealId: 'usr-4',
            aprovadorRealNome: 'Christiane Macedo',
            aprovadorRealCargo: 'Gerente de Credenciamento e Núcleo Assistencial',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'Valores conferidos conforme pacote negociado para UTI neo.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-23T10:30:00Z',
            dataDecisao: '2026-08-23T14:00:00Z',
          },
          {
            id: 'apr-004-3',
            solicitacaoId: 'req-0004',
            nivel: 3,
            nivelLabel: '3ª Alçada - Diretoria de Operações',
            cargoExigido: 'Diretora de Operações',
            aprovadorDesignadoId: 'usr-6',
            aprovadorDesignadoNome: 'Dra. Mariana Silva',
            aprovadorRealId: 'usr-6',
            aprovadorRealNome: 'Dra. Mariana Silva',
            aprovadorRealCargo: 'Diretora de Operações',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'Aprovado pelo caráter de urgência vital.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-23T14:00:00Z',
            dataDecisao: '2026-08-24T09:15:00Z',
          },
          {
            id: 'apr-004-4',
            solicitacaoId: 'req-0004',
            nivel: 4,
            nivelLabel: '4ª Alçada - Diretoria Executiva/Conselho',
            cargoExigido: 'Diretoria Executiva / Conselho',
            aprovadorDesignadoId: 'usr-8',
            aprovadorDesignadoNome: 'Janaína Mascarenhas',
            status: 'PENDENTE',
            declaracaoConflitoInteresse: false,
            dataEntrada: '2026-08-24T09:15:00Z',
          },
        ],
        documentos: [
          {
            id: 'doc-004-1',
            solicitacaoId: 'req-0004',
            tipo: 'NF_FATURA',
            nomeArquivo: 'NF-MaternidadeVida-35k.pdf',
            tamanhoBytes: 620000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: '5a105e8b9d40e1329780d62ea2265d8a1e5d576a911eb2345d1d6a8a07c58861',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-23T09:50:00Z',
          },
        ],
        createdAt: '2026-08-23T09:50:00Z',
        updatedAt: '2026-08-24T09:15:00Z',
      },

      // 5. Reprovada (Tráfego Pago Instagram R$ 2.500,00 - Acima do teto de R$ 500 reprovada com motivo registrado)
      {
        id: 'req-0005',
        numero: 'FIN-ALC-0005/2026',
        sequencial: 5,
        ano: 2026,
        dataSolicitacao: '2026-08-18',
        areaSolicitante: 'Comunicação e Marketing',
        centroCusto: 'CC-4040 - Marketing',
        solicitanteId: 'usr-1',
        solicitanteNome: 'Raquel Marimon',
        solicitanteCargo: 'Analista de Gente e Gestão',
        solicitanteEmail: 'raquel.marimon@sbsaude.com.br',
        processoId: 'proc-33',
        processoNome: 'Tráfego Pago (Instagram)',
        fornecedorFavorecido: 'Meta Platforms Inc.',
        cpfCnpj: '13.347.016/0001-17',
        objetoDespesa: 'Campanha de tráfego pago em Instagram para captação de novas vidas no plano individual',
        valorTotal: 2500.0,
        natureza: 'EVENTUAL',
        formaPagamento: 'CARTAO',
        parcelamento: false,
        dataVencimento: '2026-08-30',
        diasUteisAteVencimento: 2,
        alertaVencimentoProximo: true,
        rubricaOrcamentaria: '3.2.05.01 - Mídia e Publicidade Online',
        previstoNoOrcamento: false,
        justificativaNaoPrevisto: 'Oportunidade pontual de campanha pós-inauguração de nova clínica',
        saldoDisponivel: true,
        dadosBancarios: {
          banco: 'Cartão Corporativo',
          agencia: '0001',
          contaCorrente: 'Cartão Final 9921',
          titular: 'SB Saúde',
        },
        faixaValorCalculada: 'ATE_5K',
        faixaValorLabel: 'até R$ 5 mil',
        nivelRisco: 'ALTO',
        criteriosRisco: {
          assistencial: false,
          regulatorioAns: false,
          financeiro: true,
          reputacional: true,
        },
        alcadaAplicavelMaxima: 2,
        alcadaAplicavelLabel: '2ª (Gerência)',
        matrizAlcadaId: 'mtz-00',
        matrizAlcadaCodigo: 'POL-DIR-01',
        matrizAlcadaVersao: 'Rev. 00',
        regraAlcadaId: 'rule-33',
        tetoMensalProcesso: 500,
        tetoMensalAcumuladoAtual: 2500,
        tetoMensalEstourado: true,
        declaracaoSegregacaoFuncoes: true,
        declaracaoRegraQuatroOlhos: true,
        declaracaoProibicaoFracionamento: true,
        declaracaoAusenciaConflito: true,
        declaracaoAprovacaoPreviaCompromisso: true,
        status: 'REPROVADA',
        cadeiaAprovacao: [
          {
            id: 'apr-005-1',
            solicitacaoId: 'req-0005',
            nivel: 1,
            nivelLabel: '1ª Alçada - Gerente de COM & MKT',
            cargoExigido: 'Gerente de COM & MKT',
            aprovadorDesignadoId: 'usr-5',
            aprovadorDesignadoNome: 'Dr. Carlos Eduardo',
            aprovadorRealId: 'usr-5',
            aprovadorRealNome: 'Dr. Carlos Eduardo',
            aprovadorRealCargo: 'Gerente de COM & MKT',
            status: 'REPROVADO',
            decisao: 'REPROVADO',
            justificativa: 'Reprovado por ultrapassar o teto mensal da POL-DIR-01 (R$ 500,00) sem previsão orçamentária aprovada pela Diretoria Financeira.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-18T11:00:00Z',
            dataDecisao: '2026-08-18T16:20:00Z',
          },
        ],
        documentos: [],
        createdAt: '2026-08-18T10:40:00Z',
        updatedAt: '2026-08-18T16:20:00Z',
      },

      // 6. Devolvida pelo Financeiro (Faltando Certidões Negativas e cálculo de retenção de ISS)
      {
        id: 'req-0006',
        numero: 'FIN-ALC-0006/2026',
        sequencial: 6,
        ano: 2026,
        dataSolicitacao: '2026-08-19',
        areaSolicitante: 'Gente e Gestão',
        centroCusto: 'CC-1010 - Recursos Humanos',
        solicitanteId: 'usr-1',
        solicitanteNome: 'Raquel Marimon',
        solicitanteCargo: 'Analista de Gente e Gestão',
        solicitanteEmail: 'raquel.marimon@sbsaude.com.br',
        processoId: 'proc-30',
        processoNome: 'Contratação de fornecedores para atender as demandas administrativas e recursos humanos',
        processoContratoNumero: 'CTR-LIMPEZA-2026/02',
        fornecedorFavorecido: 'Limpeza & Facilities Premier Serviços EIRELI',
        cpfCnpj: '22.333.444/0001-55',
        objetoDespesa: 'Prestação de serviços de sanitização e higienização das instalações da sede administrativa',
        valorTotal: 2800.0,
        natureza: 'EVENTUAL',
        formaPagamento: 'BOLETO',
        parcelamento: false,
        dataVencimento: '2026-09-01',
        diasUteisAteVencimento: 3,
        alertaVencimentoProximo: true,
        rubricaOrcamentaria: '3.2.01.04 - Conservação e Limpeza Predial',
        previstoNoOrcamento: true,
        saldoDisponivel: true,
        dadosBancarios: {
          banco: '104 - Caixa Econômica',
          agencia: '0233',
          contaCorrente: '5566-7',
          titular: 'Limpeza & Facilities Premier',
        },
        faixaValorCalculada: 'ATE_5K',
        faixaValorLabel: 'até R$ 5 mil',
        nivelRisco: 'MEDIO',
        criteriosRisco: {
          assistencial: false,
          regulatorioAns: false,
          financeiro: true,
          reputacional: false,
        },
        alcadaAplicavelMaxima: 2,
        alcadaAplicavelLabel: '2ª (Gerência)',
        matrizAlcadaId: 'mtz-00',
        matrizAlcadaCodigo: 'POL-DIR-01',
        matrizAlcadaVersao: 'Rev. 00',
        regraAlcadaId: 'rule-30',
        tetoMensalProcesso: 3000,
        tetoMensalAcumuladoAtual: 2800,
        tetoMensalEstourado: false,
        declaracaoSegregacaoFuncoes: true,
        declaracaoRegraQuatroOlhos: true,
        declaracaoProibicaoFracionamento: true,
        declaracaoAusenciaConflito: true,
        declaracaoAprovacaoPreviaCompromisso: true,
        status: 'DEVOLVIDA_FINANCEIRO',
        etapaAtualNivel: 'FINANCEIRO',
        cadeiaAprovacao: [
          {
            id: 'apr-006-1',
            solicitacaoId: 'req-0006',
            nivel: 1,
            nivelLabel: '1ª Alçada - Coord. Gente e Gestão',
            cargoExigido: 'Coord. Gente e Gestão',
            aprovadorDesignadoId: 'usr-3',
            aprovadorDesignadoNome: 'Janine Sena',
            aprovadorRealId: 'usr-3',
            aprovadorRealNome: 'Janine Sena',
            aprovadorRealCargo: 'Coordenadora de Finanças',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'Serviço executado conforme cronograma mensal.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-19T10:00:00Z',
            dataDecisao: '2026-08-19T11:30:00Z',
          },
          {
            id: 'apr-006-2',
            solicitacaoId: 'req-0006',
            nivel: 2,
            nivelLabel: '2ª Alçada - Diretoria de Operações',
            cargoExigido: 'Diretora de Operações',
            aprovadorDesignadoId: 'usr-6',
            aprovadorDesignadoNome: 'Dra. Mariana Silva',
            aprovadorRealId: 'usr-6',
            aprovadorRealNome: 'Dra. Mariana Silva',
            aprovadorRealCargo: 'Diretora de Operações',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'De acordo.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-19T11:30:00Z',
            dataDecisao: '2026-08-19T15:00:00Z',
          },
        ],
        conferenciaFinanceira: {
          id: 'conf-006',
          solicitacaoId: 'req-0006',
          dataRecebimento: '2026-08-20T08:00:00Z',
          responsavelId: 'usr-9',
          responsavelNome: 'Patrícia Mendes',
          nfFaturaConferida: true,
          contratoConferido: true,
          cotacoesConferidas: false,
          boletoConferido: true,
          certidoesConferidas: false,
          retencaoISS: true,
          retencaoINSS: true,
          retencaoIRRF: false,
          retencaoPIS_COFINS_CSLL: false,
          retencaoNaoAplicavel: false,
          valorBruto: 2800.0,
          valorRetencoes: 308.0,
          valorLiquido: 2492.0,
          status: 'DEVOLVIDO_AREA',
          pendenciasObservacoes: 'Devolvido para a área: CND Municipal vencida e ausência de destaque de retenção de ISS no corpo da nota fiscal.',
          dataConferencia: '2026-08-20T14:30:00Z',
        },
        documentos: [
          {
            id: 'doc-006-1',
            solicitacaoId: 'req-0006',
            tipo: 'NF_FATURA',
            nomeArquivo: 'NF-Premier-Limpeza.pdf',
            tamanhoBytes: 310000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: '99e634b8c9d0124a91924512e345892019ab3821094857210984572019485720',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-19T09:30:00Z',
          },
        ],
        createdAt: '2026-08-19T09:30:00Z',
        updatedAt: '2026-08-20T14:30:00Z',
      },

      // 7. Liberada e Paga pela Tesouraria (Reembolso R$ 4.500,00 - Completa com comprovante de transferência)
      {
        id: 'req-0007',
        numero: 'FIN-ALC-0007/2026',
        sequencial: 7,
        ano: 2026,
        dataSolicitacao: '2026-08-15',
        areaSolicitante: 'Núcleo Assistencial',
        centroCusto: 'CC-2020 - Rede Credenciada',
        solicitanteId: 'usr-1',
        solicitanteNome: 'Raquel Marimon',
        solicitanteCargo: 'Analista de Gente e Gestão',
        solicitanteEmail: 'raquel.marimon@sbsaude.com.br',
        processoId: 'proc-13',
        processoNome: 'Reembolso',
        fornecedorFavorecido: 'Dra. Beatriz Fontana (Médica Cooperada Reembolso)',
        cpfCnpj: '333.444.555-66',
        objetoDespesa: 'Reembolso de consulta e ecocardiograma fetal fora da área de abrangência conforme cláusula 14 do contrato',
        valorTotal: 4500.0,
        natureza: 'EVENTUAL',
        formaPagamento: 'TED_PIX',
        parcelamento: false,
        dataVencimento: '2026-08-26',
        diasUteisAteVencimento: 0,
        alertaVencimentoProximo: false,
        rubricaOrcamentaria: '3.1.05.02 - Reembolsos Médicos de Beneficiários',
        previstoNoOrcamento: true,
        saldoDisponivel: true,
        dadosBancarios: {
          banco: '260 - Nubank',
          agencia: '0001',
          contaCorrente: '908123-4',
          chavePix: '333.444.555-66',
          titular: 'Beatriz Fontana',
        },
        faixaValorCalculada: 'ATE_5K',
        faixaValorLabel: 'até R$ 5 mil',
        nivelRisco: 'MEDIO',
        criteriosRisco: {
          assistencial: true,
          regulatorioAns: true,
          financeiro: false,
          reputacional: false,
        },
        alcadaAplicavelMaxima: 1,
        alcadaAplicavelLabel: '1ª (Coord./Superv.)',
        matrizAlcadaId: 'mtz-00',
        matrizAlcadaCodigo: 'POL-DIR-01',
        matrizAlcadaVersao: 'Rev. 00',
        regraAlcadaId: 'rule-13',
        tetoMensalProcesso: 20000,
        tetoMensalAcumuladoAtual: 14500,
        tetoMensalEstourado: false,
        declaracaoSegregacaoFuncoes: true,
        declaracaoRegraQuatroOlhos: true,
        declaracaoProibicaoFracionamento: true,
        declaracaoAusenciaConflito: true,
        declaracaoAprovacaoPreviaCompromisso: true,
        status: 'PAGAMENTO_EFETUADO',
        etapaAtualNivel: 'CONCLUIDO',
        cadeiaAprovacao: [
          {
            id: 'apr-007-1',
            solicitacaoId: 'req-0007',
            nivel: 1,
            nivelLabel: '1ª Alçada - Gerência de Núcleo Assistencial',
            cargoExigido: 'Gerente de Credenciamento e Núcleo Assistencial',
            aprovadorDesignadoId: 'usr-4',
            aprovadorDesignadoNome: 'Christiane Macedo',
            aprovadorRealId: 'usr-4',
            aprovadorRealNome: 'Christiane Macedo',
            aprovadorRealCargo: 'Gerente de Credenciamento e Núcleo Assistencial',
            status: 'APROVADO',
            decisao: 'APROVADO',
            justificativa: 'Comprovantes fiscais e laudo médico anexados, reembolso integral cabível.',
            declaracaoConflitoInteresse: true,
            dataEntrada: '2026-08-15T11:00:00Z',
            dataDecisao: '2026-08-15T15:00:00Z',
          },
        ],
        conferenciaFinanceira: {
          id: 'conf-007',
          solicitacaoId: 'req-0007',
          dataRecebimento: '2026-08-16T08:00:00Z',
          responsavelId: 'usr-9',
          responsavelNome: 'Patrícia Mendes',
          nfFaturaConferida: true,
          contratoConferido: true,
          cotacoesConferidas: false,
          boletoConferido: false,
          certidoesConferidas: true,
          retencaoISS: false,
          retencaoINSS: false,
          retencaoIRRF: false,
          retencaoPIS_COFINS_CSLL: false,
          retencaoNaoAplicavel: true,
          valorBruto: 4500.0,
          valorRetencoes: 0,
          valorLiquido: 4500.0,
          status: 'LIBERADO_PAGAMENTO',
          pendenciasObservacoes: 'Conferência realizada e documentação de reembolso regular.',
          dataConferencia: '2026-08-16T10:00:00Z',
        },
        registroPagamento: {
          id: 'pay-007',
          solicitacaoId: 'req-0007',
          dataPagamento: '2026-08-16',
          responsavelTesourariaId: 'usr-10',
          responsavelTesourariaNome: 'Fernando Rocha',
          responsavelTesourariaCargo: 'Coordenador de Tesouraria',
          bancoUtilizado: '341 - Itaú Unibanco',
          agenciaUtilizada: '0982',
          contaUtilizada: '10293-8',
          formaEfetivaPagamento: 'TED_PIX',
          numeroComprovante: 'PIX-20260816-991204859',
          documentoComprovanteUrl: '#',
          observacoes: 'Transferência PIX liquidada com sucesso.',
          registradoEm: '2026-08-16T14:30:00Z',
        },
        documentos: [
          {
            id: 'doc-007-1',
            solicitacaoId: 'req-0007',
            tipo: 'NF_FATURA',
            nomeArquivo: 'Recibo_Medico_BeatrizFontana.pdf',
            tamanhoBytes: 210000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: 'c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-15T10:00:00Z',
          },
        ],
        createdAt: '2026-08-15T10:00:00Z',
        updatedAt: '2026-08-16T14:30:00Z',
      },

      // 8. Possible Split Detected (Solicitação de Consultoria RH para mesmo fornecedor dentro da janela de 30 dias)
      {
        id: 'req-0008',
        numero: 'FIN-ALC-0008/2026',
        sequencial: 8,
        ano: 2026,
        dataSolicitacao: '2026-08-25',
        areaSolicitante: 'Gente e Gestão',
        centroCusto: 'CC-1010 - Recursos Humanos',
        solicitanteId: 'usr-1',
        solicitanteNome: 'Raquel Marimon',
        solicitanteCargo: 'Analista de Gente e Gestão',
        solicitanteEmail: 'raquel.marimon@sbsaude.com.br',
        processoId: 'proc-31',
        processoNome: 'Contratação de treinamentos e consultorias de RH dentro do orçamento',
        fornecedorFavorecido: 'Inovar Treinamentos Corporativos Ltda',
        cpfCnpj: '19.888.777/0001-33',
        objetoDespesa: 'Módulo 2 - Treinamento de Liderança e Gestão de Pessoas para Supervisores',
        valorTotal: 580.0,
        natureza: 'EVENTUAL',
        formaPagamento: 'BOLETO',
        parcelamento: false,
        dataVencimento: '2026-09-12',
        diasUteisAteVencimento: 12,
        alertaVencimentoProximo: false,
        rubricaOrcamentaria: '3.2.03.01 - Capacitação e Treinamentos',
        previstoNoOrcamento: true,
        saldoDisponivel: true,
        dadosBancarios: {
          banco: '237 - Bradesco',
          agencia: '1102',
          contaCorrente: '44556-9',
          titular: 'Inovar Treinamentos',
        },
        faixaValorCalculada: 'ATE_5K',
        faixaValorLabel: 'até R$ 5 mil',
        nivelRisco: 'BAIXO',
        criteriosRisco: {
          assistencial: false,
          regulatorioAns: false,
          financeiro: false,
          reputacional: false,
        },
        alcadaAplicavelMaxima: 1,
        alcadaAplicavelLabel: '1ª (Coord./Superv.)',
        matrizAlcadaId: 'mtz-00',
        matrizAlcadaCodigo: 'POL-DIR-01',
        matrizAlcadaVersao: 'Rev. 00',
        regraAlcadaId: 'rule-31',
        tetoMensalProcesso: 2400,
        tetoMensalAcumuladoAtual: 1160,
        tetoMensalEstourado: false,
        declaracaoSegregacaoFuncoes: true,
        declaracaoRegraQuatroOlhos: true,
        declaracaoProibicaoFracionamento: true,
        declaracaoAusenciaConflito: true,
        declaracaoAprovacaoPreviaCompromisso: true,
        analiseFracionamento: {
          possivelFracionamentoIdentificado: true,
          solicitacoesRelacionadasIds: ['req-0008-prev'],
          solicitacoesRelacionadasNumeros: ['FIN-ALC-0000/2026'],
          valorTotalAgrupado: 1160.0,
          criteriosCoincidentes: [
            'Mesmo CNPJ (19.888.777/0001-33)',
            'Mesmo Centro de Custo (CC-1010)',
            'Mesmo Objeto/Processo',
            'Janela inferior a 30 dias (Módulo 1 contratado há 8 dias por R$ 580,00)',
          ],
          observacao: 'Alerta de Fracionamento Potencial: A soma das duas solicitações para o mesmo fornecedor atinge R$ 1.160,00. O sistema exige ciência formal e análise da 2ª alçada.',
        },
        status: 'AGUARDANDO_1_ALCADA',
        etapaAtualNivel: 1,
        cadeiaAprovacao: [
          {
            id: 'apr-008-1',
            solicitacaoId: 'req-0008',
            nivel: 1,
            nivelLabel: '1ª Alçada - Coord. Gente e Gestão',
            cargoExigido: 'Coord. Gente e Gestão',
            aprovadorDesignadoId: 'usr-3',
            aprovadorDesignadoNome: 'Janine Sena',
            status: 'PENDENTE',
            declaracaoConflitoInteresse: false,
            dataEntrada: '2026-08-25T14:00:00Z',
          },
        ],
        documentos: [
          {
            id: 'doc-008-1',
            solicitacaoId: 'req-0008',
            tipo: 'PROPOSTA',
            nomeArquivo: 'Proposta_Inovar_Modulo2.pdf',
            tamanhoBytes: 190000,
            mimeType: 'application/pdf',
            url: '#',
            hashSha256: '71c828d1165a2872e42442436d4f9b2d075ec9bc5ef2b49cb246d88c279430c2',
            uploadedBy: { id: 'usr-1', name: 'Raquel Marimon', email: 'raquel.marimon@sbsaude.com.br' },
            uploadedAt: '2026-08-25T13:50:00Z',
          },
        ],
        createdAt: '2026-08-25T13:50:00Z',
        updatedAt: '2026-08-25T14:00:00Z',
      },
    ];

    // 5. Seed Initial Audit Logs
    this.auditLogs = [
      {
        id: 'aud-001',
        entidade: 'MATRIZ_ALCADA',
        entidadeId: 'mtz-00',
        acao: 'PUBLICACAO_MATRIZ',
        descricao: 'Publicação oficial da Matriz de Alçada POL-DIR-01 Rev. 00 aprovada pela Diretoria Executiva (Vigência 07/07/2026 a 07/07/2028).',
        usuarioId: 'usr-11',
        usuarioNome: 'Vanessa Duarte',
        usuarioEmail: 'vanessa.duarte@sbsaude.com.br',
        usuarioCargo: 'Gerente de Governança e SGQ',
        usuarioArea: 'Governança e Qualidade',
        valoresPosteriores: { versao: 'Rev. 00', vigencia: '07/07/2026 - 07/07/2028', totalRegras: 34 },
        ipAddress: '192.168.10.1',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
        timestamp: '2026-07-07T10:00:00Z',
      },
      {
        id: 'aud-002',
        solicitacaoId: 'req-0003',
        solicitacaoNumero: 'FIN-ALC-0003/2026',
        entidade: 'SOLICITACAO',
        entidadeId: 'req-0003',
        acao: 'CRIACAO_SOLICITACAO',
        descricao: 'Criação da solicitação FIN-ALC-0003/2026 para Hospital Santa Bárbara de São Paulo S/A no valor de R$ 180.000,00.',
        usuarioId: 'usr-1',
        usuarioNome: 'Raquel Marimon',
        usuarioEmail: 'raquel.marimon@sbsaude.com.br',
        usuarioCargo: 'Analista de Gente e Gestão',
        usuarioArea: 'Gente e Gestão',
        valoresPosteriores: { valorTotal: 180000.0, processo: 'proc-03', risco: 'ALTO' },
        ipAddress: '192.168.10.15',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
        timestamp: '2026-08-22T08:30:00Z',
      },
      {
        id: 'aud-003',
        solicitacaoId: 'req-0003',
        solicitacaoNumero: 'FIN-ALC-0003/2026',
        entidade: 'APROVACAO',
        entidadeId: 'apr-003-1',
        acao: 'APROVACAO_1_ALCADA',
        descricao: '1ª Alçada aprovada por Christiane Macedo (Gerente de Credenciamento e Núcleo Assistencial). Declaração de não conflito de interesse confirmada.',
        usuarioId: 'usr-4',
        usuarioNome: 'Christiane Macedo',
        usuarioEmail: 'christiane.macedo@sbsaude.com.br',
        usuarioCargo: 'Gerente de Credenciamento e Núcleo Assistencial',
        usuarioArea: 'Núcleo Assistencial',
        valoresAnteriores: { status: 'PENDENTE' },
        valoresPosteriores: { status: 'APROVADO', conflitoInteresse: false },
        ipAddress: '192.168.10.45',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
        timestamp: '2026-08-22T11:00:00Z',
      },
      {
        id: 'aud-004',
        solicitacaoId: 'req-0003',
        solicitacaoNumero: 'FIN-ALC-0003/2026',
        entidade: 'APROVACAO',
        entidadeId: 'apr-003-2',
        acao: 'APROVACAO_2_ALCADA',
        descricao: '2ª Alçada aprovada por Dra. Mariana Silva (Diretora de Operações). Declaração de não conflito de interesse confirmada.',
        usuarioId: 'usr-6',
        usuarioNome: 'Dra. Mariana Silva',
        usuarioEmail: 'mariana.silva@sbsaude.com.br',
        usuarioCargo: 'Diretora de Operações',
        usuarioArea: 'Diretoria de Operações',
        valoresAnteriores: { status: 'PENDENTE' },
        valoresPosteriores: { status: 'APROVADO', conflitoInteresse: false },
        ipAddress: '192.168.10.88',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
        timestamp: '2026-08-23T15:30:00Z',
      },
      {
        id: 'aud-005',
        solicitacaoId: 'req-0007',
        solicitacaoNumero: 'FIN-ALC-0007/2026',
        entidade: 'PAGAMENTO',
        entidadeId: 'pay-007',
        acao: 'REGISTRO_PAGAMENTO_TESOURARIA',
        descricao: 'Pagamento liquidado via PIX comprovante PIX-20260816-991204859 no valor de R$ 4.500,00 por Fernando Rocha (Coordenador de Tesouraria).',
        usuarioId: 'usr-10',
        usuarioNome: 'Fernando Rocha',
        usuarioEmail: 'fernando.rocha@sbsaude.com.br',
        usuarioCargo: 'Coordenador de Tesouraria',
        usuarioArea: 'Tesouraria',
        valoresPosteriores: { valor: 4500.0, comprovante: 'PIX-20260816-991204859', status: 'PAGAMENTO_EFETUADO' },
        ipAddress: '192.168.10.99',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
        timestamp: '2026-08-16T14:30:00Z',
      },
    ];

    // 6. Seed Notifications
    this.notifications = [
      {
        id: 'notif-1',
        userId: 'usr-7',
        title: 'Aprovação de 3ª Alçada Pendente',
        message: 'A solicitação FIN-ALC-0003/2026 no valor de R$ 180.000,00 (Hospital Santa Bárbara) aguarda sua decisão de 3ª Alçada.',
        tipo: 'URGENTE',
        solicitacaoId: 'req-0003',
        solicitacaoNumero: 'FIN-ALC-0003/2026',
        lida: false,
        createdAt: '2026-08-23T15:30:00Z',
      },
      {
        id: 'notif-2',
        userId: 'usr-8',
        title: 'Aprovação de 4ª Alçada Pendente',
        message: 'A solicitação FIN-ALC-0004/2026 no valor de R$ 35.000,00 (Partos Emergenciais) requer aprovação da Diretoria Executiva.',
        tipo: 'URGENTE',
        solicitacaoId: 'req-0004',
        solicitacaoNumero: 'FIN-ALC-0004/2026',
        lida: false,
        createdAt: '2026-08-24T09:15:00Z',
      },
      {
        id: 'notif-3',
        userId: 'usr-1',
        title: 'Solicitação Devolvida pelo Financeiro',
        message: 'A solicitação FIN-ALC-0006/2026 foi devolvida pelo Financeiro: CND Municipal vencida.',
        tipo: 'AVISO',
        solicitacaoId: 'req-0006',
        solicitacaoNumero: 'FIN-ALC-0006/2026',
        lida: false,
        createdAt: '2026-08-20T14:30:00Z',
      },
      {
        id: 'notif-4',
        userId: 'usr-3',
        title: 'Alerta de Possível Fracionamento',
        message: 'Identificado possível fracionamento na solicitação FIN-ALC-0008/2026 para o fornecedor Inovar Treinamentos.',
        tipo: 'AVISO',
        solicitacaoId: 'req-0008',
        solicitacaoNumero: 'FIN-ALC-0008/2026',
        lida: false,
        createdAt: '2026-08-25T14:00:00Z',
      },
    ];
  }

  // --- Transactions & Helpers ---

  getNextRequestNumber(): { numero: string; sequencial: number; ano: number } {
    const currentYear = new Date().getFullYear();
    const requestsThisYear = this.requests.filter((r) => r.ano === currentYear);
    const maxSeq = requestsThisYear.reduce((max, r) => Math.max(max, r.sequencial), 0);
    const sequencial = maxSeq + 1;
    const padded = String(sequencial).padStart(4, '0');
    return {
      numero: `FIN-ALC-${padded}/${currentYear}`,
      sequencial,
      ano: currentYear,
    };
  }

  addAuditLog(log: Omit<AuditLog, 'id' | 'timestamp'>): AuditLog {
    const newLog: AuditLog = {
      id: `aud-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      ...log,
      timestamp: new Date().toISOString(),
    };
    // Logs are strictly immutable: append-only
    this.auditLogs.unshift(newLog);
    // Persist to Firestore asynchronously (fire-and-forget)
    this.syncToFirestore('auditLogs', newLog.id, newLog).catch(e =>
      console.error('[DB] Falha ao persistir auditLog no Firestore:', e)
    );
    return newLog;
  }

  addNotification(notif: Omit<SystemNotification, 'id' | 'createdAt' | 'lida'>): SystemNotification {
    const newNotif: SystemNotification = {
      id: `notif-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      ...notif,
      lida: false,
      createdAt: new Date().toISOString(),
    };
    this.notifications.unshift(newNotif);
    // Persist to Firestore asynchronously (fire-and-forget)
    this.syncToFirestore('notifications', newNotif.id, newNotif).catch(e =>
      console.error('[DB] Falha ao persistir notification no Firestore:', e)
    );
    return newNotif;
  }
}

export const db = new Database();
